/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CustomApiResponseAccountSettingResponse,
  CustomApiResponseObject,
  CustomApiResponseVoid,
  GetServiceOrderDetail400Response,
  UpdateEmailRequest,
  UpdateUsernameRequest,
} from '../models/index';
import {
    CustomApiResponseAccountSettingResponseFromJSON,
    CustomApiResponseAccountSettingResponseToJSON,
    CustomApiResponseObjectFromJSON,
    CustomApiResponseObjectToJSON,
    CustomApiResponseVoidFromJSON,
    CustomApiResponseVoidToJSON,
    GetServiceOrderDetail400ResponseFromJSON,
    GetServiceOrderDetail400ResponseToJSON,
    UpdateEmailRequestFromJSON,
    UpdateEmailRequestToJSON,
    UpdateUsernameRequestFromJSON,
    UpdateUsernameRequestToJSON,
} from '../models/index';

export interface UpdateEmailRequestRequest {
    updateEmailRequest: UpdateEmailRequest;
}

export interface UpdateUsernameOperationRequest {
    updateUsernameRequest: UpdateUsernameRequest;
}

export interface VerifyEmailChangeRequest {
    token: string;
}

/**
 * 
 */
export class AccountSettingApi extends runtime.BaseAPI {

    /**
     */
    async getAccountSettingsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseAccountSettingResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/account/settings`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseAccountSettingResponseFromJSON(jsonValue));
    }

    /**
     */
    async getAccountSettings(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseAccountSettingResponse> {
        const response = await this.getAccountSettingsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async updateEmailRequestRaw(requestParameters: UpdateEmailRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseVoid>> {
        if (requestParameters['updateEmailRequest'] == null) {
            throw new runtime.RequiredError(
                'updateEmailRequest',
                'Required parameter "updateEmailRequest" was null or undefined when calling updateEmailRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/account/settings/email/request-change`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateEmailRequestToJSON(requestParameters['updateEmailRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseVoidFromJSON(jsonValue));
    }

    /**
     */
    async updateEmailRequest(requestParameters: UpdateEmailRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseVoid> {
        const response = await this.updateEmailRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateUsernameRaw(requestParameters: UpdateUsernameOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseAccountSettingResponse>> {
        if (requestParameters['updateUsernameRequest'] == null) {
            throw new runtime.RequiredError(
                'updateUsernameRequest',
                'Required parameter "updateUsernameRequest" was null or undefined when calling updateUsername().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/account/settings/username`;

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateUsernameRequestToJSON(requestParameters['updateUsernameRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseAccountSettingResponseFromJSON(jsonValue));
    }

    /**
     */
    async updateUsername(requestParameters: UpdateUsernameOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseAccountSettingResponse> {
        const response = await this.updateUsernameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async verifyEmailChangeRaw(requestParameters: VerifyEmailChangeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseVoid>> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling verifyEmailChange().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['token'] != null) {
            queryParameters['token'] = requestParameters['token'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/account/settings/email/verify-change`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseVoidFromJSON(jsonValue));
    }

    /**
     */
    async verifyEmailChange(requestParameters: VerifyEmailChangeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseVoid> {
        const response = await this.verifyEmailChangeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
