/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CustomApiResponseListAdministrativeUnitResponse,
  CustomApiResponseObject,
  GetServiceOrderDetail400Response,
} from '../models/index';
import {
    CustomApiResponseListAdministrativeUnitResponseFromJSON,
    CustomApiResponseListAdministrativeUnitResponseToJSON,
    CustomApiResponseObjectFromJSON,
    CustomApiResponseObjectToJSON,
    GetServiceOrderDetail400ResponseFromJSON,
    GetServiceOrderDetail400ResponseToJSON,
} from '../models/index';

export interface GetAdministrativeUnitsRequest {
    level: GetAdministrativeUnitsLevelEnum;
    parentCode?: string;
}

/**
 * 
 */
export class AdministrativeUnitControllerApi extends runtime.BaseAPI {

    /**
     */
    async getAdministrativeUnitsRaw(requestParameters: GetAdministrativeUnitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseListAdministrativeUnitResponse>> {
        if (requestParameters['level'] == null) {
            throw new runtime.RequiredError(
                'level',
                'Required parameter "level" was null or undefined when calling getAdministrativeUnits().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['level'] != null) {
            queryParameters['level'] = requestParameters['level'];
        }

        if (requestParameters['parentCode'] != null) {
            queryParameters['parentCode'] = requestParameters['parentCode'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/common/administrative-units`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseListAdministrativeUnitResponseFromJSON(jsonValue));
    }

    /**
     */
    async getAdministrativeUnits(requestParameters: GetAdministrativeUnitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseListAdministrativeUnitResponse> {
        const response = await this.getAdministrativeUnitsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetAdministrativeUnitsLevelEnum = {
    Province: 'PROVINCE',
    District: 'DISTRICT',
    Ward: 'WARD'
} as const;
export type GetAdministrativeUnitsLevelEnum = typeof GetAdministrativeUnitsLevelEnum[keyof typeof GetAdministrativeUnitsLevelEnum];
