/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AppointmentRequest,
  CustomApiResponseAppointmentResponse,
  CustomApiResponseObject,
  CustomApiResponsePageAppointmentResponse,
  CustomApiResponseVoid,
  GetServiceOrderDetail400Response,
  SearchFilter,
} from '../models/index';
import {
    AppointmentRequestFromJSON,
    AppointmentRequestToJSON,
    CustomApiResponseAppointmentResponseFromJSON,
    CustomApiResponseAppointmentResponseToJSON,
    CustomApiResponseObjectFromJSON,
    CustomApiResponseObjectToJSON,
    CustomApiResponsePageAppointmentResponseFromJSON,
    CustomApiResponsePageAppointmentResponseToJSON,
    CustomApiResponseVoidFromJSON,
    CustomApiResponseVoidToJSON,
    GetServiceOrderDetail400ResponseFromJSON,
    GetServiceOrderDetail400ResponseToJSON,
    SearchFilterFromJSON,
    SearchFilterToJSON,
} from '../models/index';

export interface Create9Request {
    appointmentRequest: AppointmentRequest;
}

export interface Delete9Request {
    appointmentId: string;
}

export interface Filter10Request {
    searchFilter: SearchFilter;
}

export interface GetById5Request {
    appointmentId: string;
}

export interface Update9Request {
    appointmentId: string;
    appointmentRequest: AppointmentRequest;
}

/**
 * 
 */
export class AppointmentManagementApi extends runtime.BaseAPI {

    /**
     */
    async create9Raw(requestParameters: Create9Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseAppointmentResponse>> {
        if (requestParameters['appointmentRequest'] == null) {
            throw new runtime.RequiredError(
                'appointmentRequest',
                'Required parameter "appointmentRequest" was null or undefined when calling create9().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/appointments`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AppointmentRequestToJSON(requestParameters['appointmentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseAppointmentResponseFromJSON(jsonValue));
    }

    /**
     */
    async create9(requestParameters: Create9Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseAppointmentResponse> {
        const response = await this.create9Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async delete9Raw(requestParameters: Delete9Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseVoid>> {
        if (requestParameters['appointmentId'] == null) {
            throw new runtime.RequiredError(
                'appointmentId',
                'Required parameter "appointmentId" was null or undefined when calling delete9().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/appointments/{appointmentId}`;
        urlPath = urlPath.replace(`{${"appointmentId"}}`, encodeURIComponent(String(requestParameters['appointmentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseVoidFromJSON(jsonValue));
    }

    /**
     */
    async delete9(requestParameters: Delete9Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseVoid> {
        const response = await this.delete9Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async filter10Raw(requestParameters: Filter10Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponsePageAppointmentResponse>> {
        if (requestParameters['searchFilter'] == null) {
            throw new runtime.RequiredError(
                'searchFilter',
                'Required parameter "searchFilter" was null or undefined when calling filter10().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/appointments/filter`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchFilterToJSON(requestParameters['searchFilter']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponsePageAppointmentResponseFromJSON(jsonValue));
    }

    /**
     */
    async filter10(requestParameters: Filter10Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponsePageAppointmentResponse> {
        const response = await this.filter10Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getById5Raw(requestParameters: GetById5Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseAppointmentResponse>> {
        if (requestParameters['appointmentId'] == null) {
            throw new runtime.RequiredError(
                'appointmentId',
                'Required parameter "appointmentId" was null or undefined when calling getById5().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/appointments/{appointmentId}`;
        urlPath = urlPath.replace(`{${"appointmentId"}}`, encodeURIComponent(String(requestParameters['appointmentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseAppointmentResponseFromJSON(jsonValue));
    }

    /**
     */
    async getById5(requestParameters: GetById5Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseAppointmentResponse> {
        const response = await this.getById5Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async update9Raw(requestParameters: Update9Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseAppointmentResponse>> {
        if (requestParameters['appointmentId'] == null) {
            throw new runtime.RequiredError(
                'appointmentId',
                'Required parameter "appointmentId" was null or undefined when calling update9().'
            );
        }

        if (requestParameters['appointmentRequest'] == null) {
            throw new runtime.RequiredError(
                'appointmentRequest',
                'Required parameter "appointmentRequest" was null or undefined when calling update9().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/appointments/{appointmentId}`;
        urlPath = urlPath.replace(`{${"appointmentId"}}`, encodeURIComponent(String(requestParameters['appointmentId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AppointmentRequestToJSON(requestParameters['appointmentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseAppointmentResponseFromJSON(jsonValue));
    }

    /**
     */
    async update9(requestParameters: Update9Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseAppointmentResponse> {
        const response = await this.update9Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
