/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CustomApiResponseDiagnosisResponse,
  CustomApiResponseObject,
  CustomApiResponsePageDiagnosisResponse,
  CustomApiResponseVoid,
  DiagnosisRequest,
  GetServiceOrderDetail400Response,
  SearchFilter,
} from '../models/index';
import {
    CustomApiResponseDiagnosisResponseFromJSON,
    CustomApiResponseDiagnosisResponseToJSON,
    CustomApiResponseObjectFromJSON,
    CustomApiResponseObjectToJSON,
    CustomApiResponsePageDiagnosisResponseFromJSON,
    CustomApiResponsePageDiagnosisResponseToJSON,
    CustomApiResponseVoidFromJSON,
    CustomApiResponseVoidToJSON,
    DiagnosisRequestFromJSON,
    DiagnosisRequestToJSON,
    GetServiceOrderDetail400ResponseFromJSON,
    GetServiceOrderDetail400ResponseToJSON,
    SearchFilterFromJSON,
    SearchFilterToJSON,
} from '../models/index';

export interface AddDiagnosisRequest {
    id: string;
    diagnosisRequest: DiagnosisRequest;
}

export interface DeleteDiagnosisRequest {
    id: string;
    diagnosisId: string;
}

export interface FilterDiagnosisRequest {
    id: string;
    searchFilter: SearchFilter;
}

export interface GetDiagnosisListRequest {
    id: string;
}

/**
 * 
 */
export class DiagnosisControllerApi extends runtime.BaseAPI {

    /**
     */
    async addDiagnosisRaw(requestParameters: AddDiagnosisRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseDiagnosisResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling addDiagnosis().'
            );
        }

        if (requestParameters['diagnosisRequest'] == null) {
            throw new runtime.RequiredError(
                'diagnosisRequest',
                'Required parameter "diagnosisRequest" was null or undefined when calling addDiagnosis().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/examinations/{id}/diagnosis`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DiagnosisRequestToJSON(requestParameters['diagnosisRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseDiagnosisResponseFromJSON(jsonValue));
    }

    /**
     */
    async addDiagnosis(requestParameters: AddDiagnosisRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseDiagnosisResponse> {
        const response = await this.addDiagnosisRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteDiagnosisRaw(requestParameters: DeleteDiagnosisRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseVoid>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteDiagnosis().'
            );
        }

        if (requestParameters['diagnosisId'] == null) {
            throw new runtime.RequiredError(
                'diagnosisId',
                'Required parameter "diagnosisId" was null or undefined when calling deleteDiagnosis().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/examinations/{id}/diagnosis/{diagnosisId}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"diagnosisId"}}`, encodeURIComponent(String(requestParameters['diagnosisId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseVoidFromJSON(jsonValue));
    }

    /**
     */
    async deleteDiagnosis(requestParameters: DeleteDiagnosisRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseVoid> {
        const response = await this.deleteDiagnosisRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async filterDiagnosisRaw(requestParameters: FilterDiagnosisRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponsePageDiagnosisResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling filterDiagnosis().'
            );
        }

        if (requestParameters['searchFilter'] == null) {
            throw new runtime.RequiredError(
                'searchFilter',
                'Required parameter "searchFilter" was null or undefined when calling filterDiagnosis().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/examinations/{id}/diagnosis/filter`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchFilterToJSON(requestParameters['searchFilter']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponsePageDiagnosisResponseFromJSON(jsonValue));
    }

    /**
     */
    async filterDiagnosis(requestParameters: FilterDiagnosisRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponsePageDiagnosisResponse> {
        const response = await this.filterDiagnosisRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getDiagnosisListRaw(requestParameters: GetDiagnosisListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseDiagnosisResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getDiagnosisList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/examinations/{id}/diagnosis`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseDiagnosisResponseFromJSON(jsonValue));
    }

    /**
     */
    async getDiagnosisList(requestParameters: GetDiagnosisListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseDiagnosisResponse> {
        const response = await this.getDiagnosisListRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
