/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CustomApiResponseLabOrderResponse,
  CustomApiResponseLabTestResultResponse,
  CustomApiResponseListLabOrderResponse,
  CustomApiResponseObject,
  CustomApiResponsePageLabOrderResponse,
  CustomApiResponsePageLabTestResultResponse,
  CustomApiResponseVoid,
  GetServiceOrderDetail400Response,
  LabOrderRequest,
  LabTestResultRequest,
  SearchFilter,
} from '../models/index';
import {
    CustomApiResponseLabOrderResponseFromJSON,
    CustomApiResponseLabOrderResponseToJSON,
    CustomApiResponseLabTestResultResponseFromJSON,
    CustomApiResponseLabTestResultResponseToJSON,
    CustomApiResponseListLabOrderResponseFromJSON,
    CustomApiResponseListLabOrderResponseToJSON,
    CustomApiResponseObjectFromJSON,
    CustomApiResponseObjectToJSON,
    CustomApiResponsePageLabOrderResponseFromJSON,
    CustomApiResponsePageLabOrderResponseToJSON,
    CustomApiResponsePageLabTestResultResponseFromJSON,
    CustomApiResponsePageLabTestResultResponseToJSON,
    CustomApiResponseVoidFromJSON,
    CustomApiResponseVoidToJSON,
    GetServiceOrderDetail400ResponseFromJSON,
    GetServiceOrderDetail400ResponseToJSON,
    LabOrderRequestFromJSON,
    LabOrderRequestToJSON,
    LabTestResultRequestFromJSON,
    LabTestResultRequestToJSON,
    SearchFilterFromJSON,
    SearchFilterToJSON,
} from '../models/index';

export interface AddOrderItemRequest {
    orderId: string;
    labTestResultRequest: LabTestResultRequest;
}

export interface Create5Request {
    labOrderRequest: LabOrderRequest;
}

export interface Delete5Request {
    orderId: string;
}

export interface DeleteOrderItemRequest {
    orderId: string;
    itemId: string;
}

export interface Filter6Request {
    searchFilter: SearchFilter;
}

export interface FilterOrderItemsRequest {
    orderId: string;
    searchFilter: SearchFilter;
}

export interface GetById2Request {
    orderId: string;
}

export interface Update5Request {
    orderId: string;
    labOrderRequest: LabOrderRequest;
}

export interface UpdateOrderItemRequest {
    itemId: string;
    labTestResultRequest: LabTestResultRequest;
}

export interface VerifyOrderItemRequest {
    itemId: string;
}

/**
 * 
 */
export class LabOrderManagementApi extends runtime.BaseAPI {

    /**
     */
    async addOrderItemRaw(requestParameters: AddOrderItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseLabTestResultResponse>> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling addOrderItem().'
            );
        }

        if (requestParameters['labTestResultRequest'] == null) {
            throw new runtime.RequiredError(
                'labTestResultRequest',
                'Required parameter "labTestResultRequest" was null or undefined when calling addOrderItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/lab-orders/{orderId}/results`;
        urlPath = urlPath.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LabTestResultRequestToJSON(requestParameters['labTestResultRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseLabTestResultResponseFromJSON(jsonValue));
    }

    /**
     */
    async addOrderItem(requestParameters: AddOrderItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseLabTestResultResponse> {
        const response = await this.addOrderItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async create5Raw(requestParameters: Create5Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseLabOrderResponse>> {
        if (requestParameters['labOrderRequest'] == null) {
            throw new runtime.RequiredError(
                'labOrderRequest',
                'Required parameter "labOrderRequest" was null or undefined when calling create5().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/lab-orders`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LabOrderRequestToJSON(requestParameters['labOrderRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseLabOrderResponseFromJSON(jsonValue));
    }

    /**
     */
    async create5(requestParameters: Create5Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseLabOrderResponse> {
        const response = await this.create5Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async delete5Raw(requestParameters: Delete5Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseVoid>> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling delete5().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/lab-orders/{orderId}`;
        urlPath = urlPath.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseVoidFromJSON(jsonValue));
    }

    /**
     */
    async delete5(requestParameters: Delete5Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseVoid> {
        const response = await this.delete5Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteOrderItemRaw(requestParameters: DeleteOrderItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseVoid>> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling deleteOrderItem().'
            );
        }

        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling deleteOrderItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/lab-orders/{orderId}/order-items/{itemId}`;
        urlPath = urlPath.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId'])));
        urlPath = urlPath.replace(`{${"itemId"}}`, encodeURIComponent(String(requestParameters['itemId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseVoidFromJSON(jsonValue));
    }

    /**
     */
    async deleteOrderItem(requestParameters: DeleteOrderItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseVoid> {
        const response = await this.deleteOrderItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async filter6Raw(requestParameters: Filter6Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponsePageLabOrderResponse>> {
        if (requestParameters['searchFilter'] == null) {
            throw new runtime.RequiredError(
                'searchFilter',
                'Required parameter "searchFilter" was null or undefined when calling filter6().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/lab-orders/filter`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchFilterToJSON(requestParameters['searchFilter']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponsePageLabOrderResponseFromJSON(jsonValue));
    }

    /**
     */
    async filter6(requestParameters: Filter6Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponsePageLabOrderResponse> {
        const response = await this.filter6Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async filterOrderItemsRaw(requestParameters: FilterOrderItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponsePageLabTestResultResponse>> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling filterOrderItems().'
            );
        }

        if (requestParameters['searchFilter'] == null) {
            throw new runtime.RequiredError(
                'searchFilter',
                'Required parameter "searchFilter" was null or undefined when calling filterOrderItems().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/lab-orders/{orderId}/results/filter`;
        urlPath = urlPath.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchFilterToJSON(requestParameters['searchFilter']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponsePageLabTestResultResponseFromJSON(jsonValue));
    }

    /**
     */
    async filterOrderItems(requestParameters: FilterOrderItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponsePageLabTestResultResponse> {
        const response = await this.filterOrderItemsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getById2Raw(requestParameters: GetById2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseLabOrderResponse>> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling getById2().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/lab-orders/{orderId}`;
        urlPath = urlPath.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseLabOrderResponseFromJSON(jsonValue));
    }

    /**
     */
    async getById2(requestParameters: GetById2Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseLabOrderResponse> {
        const response = await this.getById2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getLabOrdersForStaffTodayRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseListLabOrderResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/lab-orders/staff/today`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseListLabOrderResponseFromJSON(jsonValue));
    }

    /**
     */
    async getLabOrdersForStaffToday(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseListLabOrderResponse> {
        const response = await this.getLabOrdersForStaffTodayRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async update5Raw(requestParameters: Update5Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseLabOrderResponse>> {
        if (requestParameters['orderId'] == null) {
            throw new runtime.RequiredError(
                'orderId',
                'Required parameter "orderId" was null or undefined when calling update5().'
            );
        }

        if (requestParameters['labOrderRequest'] == null) {
            throw new runtime.RequiredError(
                'labOrderRequest',
                'Required parameter "labOrderRequest" was null or undefined when calling update5().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/lab-orders/{orderId}`;
        urlPath = urlPath.replace(`{${"orderId"}}`, encodeURIComponent(String(requestParameters['orderId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: LabOrderRequestToJSON(requestParameters['labOrderRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseLabOrderResponseFromJSON(jsonValue));
    }

    /**
     */
    async update5(requestParameters: Update5Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseLabOrderResponse> {
        const response = await this.update5Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateOrderItemRaw(requestParameters: UpdateOrderItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseLabTestResultResponse>> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling updateOrderItem().'
            );
        }

        if (requestParameters['labTestResultRequest'] == null) {
            throw new runtime.RequiredError(
                'labTestResultRequest',
                'Required parameter "labTestResultRequest" was null or undefined when calling updateOrderItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/lab-orders/results/{itemId}`;
        urlPath = urlPath.replace(`{${"itemId"}}`, encodeURIComponent(String(requestParameters['itemId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: LabTestResultRequestToJSON(requestParameters['labTestResultRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseLabTestResultResponseFromJSON(jsonValue));
    }

    /**
     */
    async updateOrderItem(requestParameters: UpdateOrderItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseLabTestResultResponse> {
        const response = await this.updateOrderItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async verifyOrderItemRaw(requestParameters: VerifyOrderItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseVoid>> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling verifyOrderItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/lab-orders/result/{itemId}/verify`;
        urlPath = urlPath.replace(`{${"itemId"}}`, encodeURIComponent(String(requestParameters['itemId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseVoidFromJSON(jsonValue));
    }

    /**
     */
    async verifyOrderItem(requestParameters: VerifyOrderItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseVoid> {
        const response = await this.verifyOrderItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
