/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CustomApiResponseMedicineResponse,
  CustomApiResponseObject,
  CustomApiResponsePageMedicineResponse,
  CustomApiResponseVoid,
  GetServiceOrderDetail400Response,
  MedicineRequest,
  SearchFilter,
} from '../models/index';
import {
    CustomApiResponseMedicineResponseFromJSON,
    CustomApiResponseMedicineResponseToJSON,
    CustomApiResponseObjectFromJSON,
    CustomApiResponseObjectToJSON,
    CustomApiResponsePageMedicineResponseFromJSON,
    CustomApiResponsePageMedicineResponseToJSON,
    CustomApiResponseVoidFromJSON,
    CustomApiResponseVoidToJSON,
    GetServiceOrderDetail400ResponseFromJSON,
    GetServiceOrderDetail400ResponseToJSON,
    MedicineRequestFromJSON,
    MedicineRequestToJSON,
    SearchFilterFromJSON,
    SearchFilterToJSON,
} from '../models/index';

export interface Create3Request {
    medicineRequest: MedicineRequest;
}

export interface Delete3Request {
    medicineId: string;
}

export interface Filter4Request {
    searchFilter: SearchFilter;
}

export interface GetByIdRequest {
    medicineId: string;
}

export interface Update3Request {
    medicineId: string;
    medicineRequest: MedicineRequest;
}

/**
 * 
 */
export class MedicineManagementApi extends runtime.BaseAPI {

    /**
     */
    async create3Raw(requestParameters: Create3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseMedicineResponse>> {
        if (requestParameters['medicineRequest'] == null) {
            throw new runtime.RequiredError(
                'medicineRequest',
                'Required parameter "medicineRequest" was null or undefined when calling create3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/medicines`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MedicineRequestToJSON(requestParameters['medicineRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseMedicineResponseFromJSON(jsonValue));
    }

    /**
     */
    async create3(requestParameters: Create3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseMedicineResponse> {
        const response = await this.create3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async delete3Raw(requestParameters: Delete3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseVoid>> {
        if (requestParameters['medicineId'] == null) {
            throw new runtime.RequiredError(
                'medicineId',
                'Required parameter "medicineId" was null or undefined when calling delete3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/medicines/{medicineId}`;
        urlPath = urlPath.replace(`{${"medicineId"}}`, encodeURIComponent(String(requestParameters['medicineId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseVoidFromJSON(jsonValue));
    }

    /**
     */
    async delete3(requestParameters: Delete3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseVoid> {
        const response = await this.delete3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async filter4Raw(requestParameters: Filter4Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponsePageMedicineResponse>> {
        if (requestParameters['searchFilter'] == null) {
            throw new runtime.RequiredError(
                'searchFilter',
                'Required parameter "searchFilter" was null or undefined when calling filter4().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/medicines/filter`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchFilterToJSON(requestParameters['searchFilter']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponsePageMedicineResponseFromJSON(jsonValue));
    }

    /**
     */
    async filter4(requestParameters: Filter4Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponsePageMedicineResponse> {
        const response = await this.filter4Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getByIdRaw(requestParameters: GetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseMedicineResponse>> {
        if (requestParameters['medicineId'] == null) {
            throw new runtime.RequiredError(
                'medicineId',
                'Required parameter "medicineId" was null or undefined when calling getById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/medicines/{medicineId}`;
        urlPath = urlPath.replace(`{${"medicineId"}}`, encodeURIComponent(String(requestParameters['medicineId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseMedicineResponseFromJSON(jsonValue));
    }

    /**
     */
    async getById(requestParameters: GetByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseMedicineResponse> {
        const response = await this.getByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async update3Raw(requestParameters: Update3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseMedicineResponse>> {
        if (requestParameters['medicineId'] == null) {
            throw new runtime.RequiredError(
                'medicineId',
                'Required parameter "medicineId" was null or undefined when calling update3().'
            );
        }

        if (requestParameters['medicineRequest'] == null) {
            throw new runtime.RequiredError(
                'medicineRequest',
                'Required parameter "medicineRequest" was null or undefined when calling update3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/medicines/{medicineId}`;
        urlPath = urlPath.replace(`{${"medicineId"}}`, encodeURIComponent(String(requestParameters['medicineId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MedicineRequestToJSON(requestParameters['medicineRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseMedicineResponseFromJSON(jsonValue));
    }

    /**
     */
    async update3(requestParameters: Update3Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseMedicineResponse> {
        const response = await this.update3Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
