/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CustomApiResponseObject,
  CustomApiResponsePagePositionResponse,
  CustomApiResponsePositionResponse,
  CustomApiResponseVoid,
  GetServiceOrderDetail400Response,
  PositionRequest,
  SearchFilter,
} from '../models/index';
import {
    CustomApiResponseObjectFromJSON,
    CustomApiResponseObjectToJSON,
    CustomApiResponsePagePositionResponseFromJSON,
    CustomApiResponsePagePositionResponseToJSON,
    CustomApiResponsePositionResponseFromJSON,
    CustomApiResponsePositionResponseToJSON,
    CustomApiResponseVoidFromJSON,
    CustomApiResponseVoidToJSON,
    GetServiceOrderDetail400ResponseFromJSON,
    GetServiceOrderDetail400ResponseToJSON,
    PositionRequestFromJSON,
    PositionRequestToJSON,
    SearchFilterFromJSON,
    SearchFilterToJSON,
} from '../models/index';

export interface Create12Request {
    positionRequest: PositionRequest;
}

export interface Delete12Request {
    id: string;
}

export interface Filter14Request {
    searchFilter: SearchFilter;
}

export interface GetById8Request {
    id: string;
}

export interface Update12Request {
    id: string;
    positionRequest: PositionRequest;
}

/**
 * 
 */
export class PositionManagementApi extends runtime.BaseAPI {

    /**
     */
    async create12Raw(requestParameters: Create12Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponsePositionResponse>> {
        if (requestParameters['positionRequest'] == null) {
            throw new runtime.RequiredError(
                'positionRequest',
                'Required parameter "positionRequest" was null or undefined when calling create12().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/positions`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PositionRequestToJSON(requestParameters['positionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponsePositionResponseFromJSON(jsonValue));
    }

    /**
     */
    async create12(requestParameters: Create12Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponsePositionResponse> {
        const response = await this.create12Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async delete12Raw(requestParameters: Delete12Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseVoid>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling delete12().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/positions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseVoidFromJSON(jsonValue));
    }

    /**
     */
    async delete12(requestParameters: Delete12Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseVoid> {
        const response = await this.delete12Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async filter14Raw(requestParameters: Filter14Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponsePagePositionResponse>> {
        if (requestParameters['searchFilter'] == null) {
            throw new runtime.RequiredError(
                'searchFilter',
                'Required parameter "searchFilter" was null or undefined when calling filter14().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/positions/filter`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchFilterToJSON(requestParameters['searchFilter']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponsePagePositionResponseFromJSON(jsonValue));
    }

    /**
     */
    async filter14(requestParameters: Filter14Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponsePagePositionResponse> {
        const response = await this.filter14Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getById8Raw(requestParameters: GetById8Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponsePositionResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getById8().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/positions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponsePositionResponseFromJSON(jsonValue));
    }

    /**
     */
    async getById8(requestParameters: GetById8Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponsePositionResponse> {
        const response = await this.getById8Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async update12Raw(requestParameters: Update12Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponsePositionResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling update12().'
            );
        }

        if (requestParameters['positionRequest'] == null) {
            throw new runtime.RequiredError(
                'positionRequest',
                'Required parameter "positionRequest" was null or undefined when calling update12().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/positions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PositionRequestToJSON(requestParameters['positionRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponsePositionResponseFromJSON(jsonValue));
    }

    /**
     */
    async update12(requestParameters: Update12Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponsePositionResponse> {
        const response = await this.update12Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
