/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CustomApiResponseListQueueTicketResponse,
  CustomApiResponseObject,
  CustomApiResponseQueueTicketResponse,
  GetServiceOrderDetail400Response,
} from '../models/index';
import {
    CustomApiResponseListQueueTicketResponseFromJSON,
    CustomApiResponseListQueueTicketResponseToJSON,
    CustomApiResponseObjectFromJSON,
    CustomApiResponseObjectToJSON,
    CustomApiResponseQueueTicketResponseFromJSON,
    CustomApiResponseQueueTicketResponseToJSON,
    GetServiceOrderDetail400ResponseFromJSON,
    GetServiceOrderDetail400ResponseToJSON,
} from '../models/index';

export interface CallQueueTicketRequest {
    queueTicketId: string;
}

export interface DoneQueueTicketRequest {
    queueTicketId: string;
}

export interface RequeueQueueTicketRequest {
    queueTicketId: string;
}

export interface ResumeQueueTicketRequest {
    queueTicketId: string;
}

export interface SkipQueueTicketRequest {
    queueTicketId: string;
}

export interface StartQueueTicketRequest {
    queueTicketId: string;
}

export interface WaitResultQueueTicketRequest {
    queueTicketId: string;
}

/**
 * 
 */
export class QueueTicketManagementApi extends runtime.BaseAPI {

    /**
     */
    async callQueueTicketRaw(requestParameters: CallQueueTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseQueueTicketResponse>> {
        if (requestParameters['queueTicketId'] == null) {
            throw new runtime.RequiredError(
                'queueTicketId',
                'Required parameter "queueTicketId" was null or undefined when calling callQueueTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/queue-tickets/{queueTicketId}/call`;
        urlPath = urlPath.replace(`{${"queueTicketId"}}`, encodeURIComponent(String(requestParameters['queueTicketId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseQueueTicketResponseFromJSON(jsonValue));
    }

    /**
     */
    async callQueueTicket(requestParameters: CallQueueTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseQueueTicketResponse> {
        const response = await this.callQueueTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async doneQueueTicketRaw(requestParameters: DoneQueueTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseQueueTicketResponse>> {
        if (requestParameters['queueTicketId'] == null) {
            throw new runtime.RequiredError(
                'queueTicketId',
                'Required parameter "queueTicketId" was null or undefined when calling doneQueueTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/queue-tickets/{queueTicketId}/done`;
        urlPath = urlPath.replace(`{${"queueTicketId"}}`, encodeURIComponent(String(requestParameters['queueTicketId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseQueueTicketResponseFromJSON(jsonValue));
    }

    /**
     */
    async doneQueueTicket(requestParameters: DoneQueueTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseQueueTicketResponse> {
        const response = await this.doneQueueTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getQueueForDoctorTodayRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseListQueueTicketResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/queue-tickets/doctor/today`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseListQueueTicketResponseFromJSON(jsonValue));
    }

    /**
     */
    async getQueueForDoctorToday(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseListQueueTicketResponse> {
        const response = await this.getQueueForDoctorTodayRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async requeueQueueTicketRaw(requestParameters: RequeueQueueTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseQueueTicketResponse>> {
        if (requestParameters['queueTicketId'] == null) {
            throw new runtime.RequiredError(
                'queueTicketId',
                'Required parameter "queueTicketId" was null or undefined when calling requeueQueueTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/queue-tickets/{queueTicketId}/requeue`;
        urlPath = urlPath.replace(`{${"queueTicketId"}}`, encodeURIComponent(String(requestParameters['queueTicketId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseQueueTicketResponseFromJSON(jsonValue));
    }

    /**
     */
    async requeueQueueTicket(requestParameters: RequeueQueueTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseQueueTicketResponse> {
        const response = await this.requeueQueueTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async resumeQueueTicketRaw(requestParameters: ResumeQueueTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseQueueTicketResponse>> {
        if (requestParameters['queueTicketId'] == null) {
            throw new runtime.RequiredError(
                'queueTicketId',
                'Required parameter "queueTicketId" was null or undefined when calling resumeQueueTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/queue-tickets/{queueTicketId}/resume`;
        urlPath = urlPath.replace(`{${"queueTicketId"}}`, encodeURIComponent(String(requestParameters['queueTicketId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseQueueTicketResponseFromJSON(jsonValue));
    }

    /**
     */
    async resumeQueueTicket(requestParameters: ResumeQueueTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseQueueTicketResponse> {
        const response = await this.resumeQueueTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async skipQueueTicketRaw(requestParameters: SkipQueueTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseQueueTicketResponse>> {
        if (requestParameters['queueTicketId'] == null) {
            throw new runtime.RequiredError(
                'queueTicketId',
                'Required parameter "queueTicketId" was null or undefined when calling skipQueueTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/queue-tickets/{queueTicketId}/skip`;
        urlPath = urlPath.replace(`{${"queueTicketId"}}`, encodeURIComponent(String(requestParameters['queueTicketId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseQueueTicketResponseFromJSON(jsonValue));
    }

    /**
     */
    async skipQueueTicket(requestParameters: SkipQueueTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseQueueTicketResponse> {
        const response = await this.skipQueueTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async startQueueTicketRaw(requestParameters: StartQueueTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseQueueTicketResponse>> {
        if (requestParameters['queueTicketId'] == null) {
            throw new runtime.RequiredError(
                'queueTicketId',
                'Required parameter "queueTicketId" was null or undefined when calling startQueueTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/queue-tickets/{queueTicketId}/start`;
        urlPath = urlPath.replace(`{${"queueTicketId"}}`, encodeURIComponent(String(requestParameters['queueTicketId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseQueueTicketResponseFromJSON(jsonValue));
    }

    /**
     */
    async startQueueTicket(requestParameters: StartQueueTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseQueueTicketResponse> {
        const response = await this.startQueueTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async waitResultQueueTicketRaw(requestParameters: WaitResultQueueTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseQueueTicketResponse>> {
        if (requestParameters['queueTicketId'] == null) {
            throw new runtime.RequiredError(
                'queueTicketId',
                'Required parameter "queueTicketId" was null or undefined when calling waitResultQueueTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/queue-tickets/{queueTicketId}/wait-result`;
        urlPath = urlPath.replace(`{${"queueTicketId"}}`, encodeURIComponent(String(requestParameters['queueTicketId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseQueueTicketResponseFromJSON(jsonValue));
    }

    /**
     */
    async waitResultQueueTicket(requestParameters: WaitResultQueueTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseQueueTicketResponse> {
        const response = await this.waitResultQueueTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
