/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CustomApiResponseObject,
  CustomApiResponseVoid,
  GetPatientById400Response,
} from '../models/index';
import {
    CustomApiResponseObjectFromJSON,
    CustomApiResponseObjectToJSON,
    CustomApiResponseVoidFromJSON,
    CustomApiResponseVoidToJSON,
    GetPatientById400ResponseFromJSON,
    GetPatientById400ResponseToJSON,
} from '../models/index';

export interface DeleteServiceOrderItemRequest {
    id: string;
    itemId: string;
}

/**
 * 
 */
export class ServiceOrderItemControllerApi extends runtime.BaseAPI {

    /**
     */
    async deleteServiceOrderItemRaw(requestParameters: DeleteServiceOrderItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseVoid>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteServiceOrderItem().'
            );
        }

        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling deleteServiceOrderItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/examinations/{id}/services/item/{itemId}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"itemId"}}`, encodeURIComponent(String(requestParameters['itemId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseVoidFromJSON(jsonValue));
    }

    /**
     */
    async deleteServiceOrderItem(requestParameters: DeleteServiceOrderItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseVoid> {
        const response = await this.deleteServiceOrderItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
