/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateServiceOrderRequest,
  CustomApiResponseListServiceOrderResponse,
  CustomApiResponseObject,
  CustomApiResponseServiceOrderResponse,
  GetPatientById400Response,
  ServiceOrderRequest,
} from '../models/index';
import {
    CreateServiceOrderRequestFromJSON,
    CreateServiceOrderRequestToJSON,
    CustomApiResponseListServiceOrderResponseFromJSON,
    CustomApiResponseListServiceOrderResponseToJSON,
    CustomApiResponseObjectFromJSON,
    CustomApiResponseObjectToJSON,
    CustomApiResponseServiceOrderResponseFromJSON,
    CustomApiResponseServiceOrderResponseToJSON,
    GetPatientById400ResponseFromJSON,
    GetPatientById400ResponseToJSON,
    ServiceOrderRequestFromJSON,
    ServiceOrderRequestToJSON,
} from '../models/index';

export interface CreateOrdersRequest {
    examId: string;
    createServiceOrderRequest: CreateServiceOrderRequest;
}

export interface CreateServiceOrderRequest {
    id: string;
    serviceOrderRequest: ServiceOrderRequest;
}

export interface GetServiceOrdersRequest {
    id: string;
}

export interface SaveOrUpdateServiceOrdersRequest {
    id: string;
    serviceOrderId: string;
    serviceOrderRequest: ServiceOrderRequest;
}

/**
 * 
 */
export class ServiceOrderControllerApi extends runtime.BaseAPI {

    /**
     */
    async createOrdersRaw(requestParameters: CreateOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseListServiceOrderResponse>> {
        if (requestParameters['examId'] == null) {
            throw new runtime.RequiredError(
                'examId',
                'Required parameter "examId" was null or undefined when calling createOrders().'
            );
        }

        if (requestParameters['createServiceOrderRequest'] == null) {
            throw new runtime.RequiredError(
                'createServiceOrderRequest',
                'Required parameter "createServiceOrderRequest" was null or undefined when calling createOrders().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/examinations/{examId}/orders`;
        urlPath = urlPath.replace(`{${"examId"}}`, encodeURIComponent(String(requestParameters['examId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateServiceOrderRequestToJSON(requestParameters['createServiceOrderRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseListServiceOrderResponseFromJSON(jsonValue));
    }

    /**
     */
    async createOrders(requestParameters: CreateOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseListServiceOrderResponse> {
        const response = await this.createOrdersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async createServiceOrderRaw(requestParameters: CreateServiceOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseServiceOrderResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createServiceOrder().'
            );
        }

        if (requestParameters['serviceOrderRequest'] == null) {
            throw new runtime.RequiredError(
                'serviceOrderRequest',
                'Required parameter "serviceOrderRequest" was null or undefined when calling createServiceOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/examinations/{id}/services`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ServiceOrderRequestToJSON(requestParameters['serviceOrderRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseServiceOrderResponseFromJSON(jsonValue));
    }

    /**
     */
    async createServiceOrder(requestParameters: CreateServiceOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseServiceOrderResponse> {
        const response = await this.createServiceOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getServiceOrdersRaw(requestParameters: GetServiceOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseServiceOrderResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getServiceOrders().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/examinations/{id}/services`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseServiceOrderResponseFromJSON(jsonValue));
    }

    /**
     */
    async getServiceOrders(requestParameters: GetServiceOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseServiceOrderResponse> {
        const response = await this.getServiceOrdersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async saveOrUpdateServiceOrdersRaw(requestParameters: SaveOrUpdateServiceOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseServiceOrderResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling saveOrUpdateServiceOrders().'
            );
        }

        if (requestParameters['serviceOrderId'] == null) {
            throw new runtime.RequiredError(
                'serviceOrderId',
                'Required parameter "serviceOrderId" was null or undefined when calling saveOrUpdateServiceOrders().'
            );
        }

        if (requestParameters['serviceOrderRequest'] == null) {
            throw new runtime.RequiredError(
                'serviceOrderRequest',
                'Required parameter "serviceOrderRequest" was null or undefined when calling saveOrUpdateServiceOrders().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/examinations/{id}/services/{serviceOrderId}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"serviceOrderId"}}`, encodeURIComponent(String(requestParameters['serviceOrderId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ServiceOrderRequestToJSON(requestParameters['serviceOrderRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseServiceOrderResponseFromJSON(jsonValue));
    }

    /**
     */
    async saveOrUpdateServiceOrders(requestParameters: SaveOrUpdateServiceOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseServiceOrderResponse> {
        const response = await this.saveOrUpdateServiceOrdersRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
