/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CustomApiResponseListServiceOrderResponse,
  CustomApiResponseObject,
  CustomApiResponsePageServiceOrderResponse,
  CustomApiResponseServiceOrderResponse,
  GetServiceOrderDetail400Response,
  SearchFilter,
  ServiceOrderRequest,
} from '../models/index';
import {
    CustomApiResponseListServiceOrderResponseFromJSON,
    CustomApiResponseListServiceOrderResponseToJSON,
    CustomApiResponseObjectFromJSON,
    CustomApiResponseObjectToJSON,
    CustomApiResponsePageServiceOrderResponseFromJSON,
    CustomApiResponsePageServiceOrderResponseToJSON,
    CustomApiResponseServiceOrderResponseFromJSON,
    CustomApiResponseServiceOrderResponseToJSON,
    GetServiceOrderDetail400ResponseFromJSON,
    GetServiceOrderDetail400ResponseToJSON,
    SearchFilterFromJSON,
    SearchFilterToJSON,
    ServiceOrderRequestFromJSON,
    ServiceOrderRequestToJSON,
} from '../models/index';

export interface GetServiceOrderDetailRequest {
    id: string;
}

export interface GetServiceOrdersForFiltersRequest {
    searchFilter: SearchFilter;
}

export interface UpdateServiceOrderRequest {
    id: string;
    serviceOrderRequest: ServiceOrderRequest;
}

/**
 * 
 */
export class ServiceOrderControllerApi extends runtime.BaseAPI {

    /**
     */
    async getServiceOrderDetailRaw(requestParameters: GetServiceOrderDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseServiceOrderResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getServiceOrderDetail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/service-orders/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseServiceOrderResponseFromJSON(jsonValue));
    }

    /**
     */
    async getServiceOrderDetail(requestParameters: GetServiceOrderDetailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseServiceOrderResponse> {
        const response = await this.getServiceOrderDetailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getServiceOrdersForFiltersRaw(requestParameters: GetServiceOrdersForFiltersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponsePageServiceOrderResponse>> {
        if (requestParameters['searchFilter'] == null) {
            throw new runtime.RequiredError(
                'searchFilter',
                'Required parameter "searchFilter" was null or undefined when calling getServiceOrdersForFilters().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/service-orders/filter`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchFilterToJSON(requestParameters['searchFilter']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponsePageServiceOrderResponseFromJSON(jsonValue));
    }

    /**
     */
    async getServiceOrdersForFilters(requestParameters: GetServiceOrdersForFiltersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponsePageServiceOrderResponse> {
        const response = await this.getServiceOrdersForFiltersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getServiceOrdersForStaffTodayRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseListServiceOrderResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/service-orders/staff/today`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseListServiceOrderResponseFromJSON(jsonValue));
    }

    /**
     */
    async getServiceOrdersForStaffToday(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseListServiceOrderResponse> {
        const response = await this.getServiceOrdersForStaffTodayRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async updateServiceOrderRaw(requestParameters: UpdateServiceOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseServiceOrderResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateServiceOrder().'
            );
        }

        if (requestParameters['serviceOrderRequest'] == null) {
            throw new runtime.RequiredError(
                'serviceOrderRequest',
                'Required parameter "serviceOrderRequest" was null or undefined when calling updateServiceOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/service-orders/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ServiceOrderRequestToJSON(requestParameters['serviceOrderRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseServiceOrderResponseFromJSON(jsonValue));
    }

    /**
     */
    async updateServiceOrder(requestParameters: UpdateServiceOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseServiceOrderResponse> {
        const response = await this.updateServiceOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
