/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CustomApiResponseObject,
  CustomApiResponsePageSpecialtyResponse,
  CustomApiResponseSpecialtyResponse,
  CustomApiResponseVoid,
  GetServiceOrderDetail400Response,
  SearchFilter,
  SpecialtyRequest,
} from '../models/index';
import {
    CustomApiResponseObjectFromJSON,
    CustomApiResponseObjectToJSON,
    CustomApiResponsePageSpecialtyResponseFromJSON,
    CustomApiResponsePageSpecialtyResponseToJSON,
    CustomApiResponseSpecialtyResponseFromJSON,
    CustomApiResponseSpecialtyResponseToJSON,
    CustomApiResponseVoidFromJSON,
    CustomApiResponseVoidToJSON,
    GetServiceOrderDetail400ResponseFromJSON,
    GetServiceOrderDetail400ResponseToJSON,
    SearchFilterFromJSON,
    SearchFilterToJSON,
    SpecialtyRequestFromJSON,
    SpecialtyRequestToJSON,
} from '../models/index';

export interface Create11Request {
    specialtyRequest: SpecialtyRequest;
}

export interface Delete11Request {
    id: string;
}

export interface Filter13Request {
    searchFilter: SearchFilter;
}

export interface GetById7Request {
    id: string;
}

export interface Update11Request {
    id: string;
    specialtyRequest: SpecialtyRequest;
}

/**
 * 
 */
export class SpecialtyManagementApi extends runtime.BaseAPI {

    /**
     */
    async create11Raw(requestParameters: Create11Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseSpecialtyResponse>> {
        if (requestParameters['specialtyRequest'] == null) {
            throw new runtime.RequiredError(
                'specialtyRequest',
                'Required parameter "specialtyRequest" was null or undefined when calling create11().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/specialties`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SpecialtyRequestToJSON(requestParameters['specialtyRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseSpecialtyResponseFromJSON(jsonValue));
    }

    /**
     */
    async create11(requestParameters: Create11Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseSpecialtyResponse> {
        const response = await this.create11Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async delete11Raw(requestParameters: Delete11Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseVoid>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling delete11().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/specialties/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseVoidFromJSON(jsonValue));
    }

    /**
     */
    async delete11(requestParameters: Delete11Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseVoid> {
        const response = await this.delete11Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async filter13Raw(requestParameters: Filter13Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponsePageSpecialtyResponse>> {
        if (requestParameters['searchFilter'] == null) {
            throw new runtime.RequiredError(
                'searchFilter',
                'Required parameter "searchFilter" was null or undefined when calling filter13().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/specialties/filter`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchFilterToJSON(requestParameters['searchFilter']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponsePageSpecialtyResponseFromJSON(jsonValue));
    }

    /**
     */
    async filter13(requestParameters: Filter13Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponsePageSpecialtyResponse> {
        const response = await this.filter13Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getById7Raw(requestParameters: GetById7Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseSpecialtyResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getById7().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/specialties/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseSpecialtyResponseFromJSON(jsonValue));
    }

    /**
     */
    async getById7(requestParameters: GetById7Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseSpecialtyResponse> {
        const response = await this.getById7Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async update11Raw(requestParameters: Update11Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseSpecialtyResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling update11().'
            );
        }

        if (requestParameters['specialtyRequest'] == null) {
            throw new runtime.RequiredError(
                'specialtyRequest',
                'Required parameter "specialtyRequest" was null or undefined when calling update11().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/specialties/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SpecialtyRequestToJSON(requestParameters['specialtyRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseSpecialtyResponseFromJSON(jsonValue));
    }

    /**
     */
    async update11(requestParameters: Update11Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseSpecialtyResponse> {
        const response = await this.update11Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
