/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CustomApiResponseObject,
  CustomApiResponsePageUserResponse,
  CustomApiResponseVoid,
  GetServiceOrderDetail400Response,
  SearchFilter,
} from '../models/index';
import {
    CustomApiResponseObjectFromJSON,
    CustomApiResponseObjectToJSON,
    CustomApiResponsePageUserResponseFromJSON,
    CustomApiResponsePageUserResponseToJSON,
    CustomApiResponseVoidFromJSON,
    CustomApiResponseVoidToJSON,
    GetServiceOrderDetail400ResponseFromJSON,
    GetServiceOrderDetail400ResponseToJSON,
    SearchFilterFromJSON,
    SearchFilterToJSON,
} from '../models/index';

export interface Filter12Request {
    searchFilter: SearchFilter;
}

export interface LockUserAccountRequest {
    userId: string;
}

export interface UnlockUserAccountRequest {
    userId: string;
}

/**
 * 
 */
export class UserManagementApi extends runtime.BaseAPI {

    /**
     */
    async filter12Raw(requestParameters: Filter12Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponsePageUserResponse>> {
        if (requestParameters['searchFilter'] == null) {
            throw new runtime.RequiredError(
                'searchFilter',
                'Required parameter "searchFilter" was null or undefined when calling filter12().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/users/filter`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SearchFilterToJSON(requestParameters['searchFilter']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponsePageUserResponseFromJSON(jsonValue));
    }

    /**
     */
    async filter12(requestParameters: Filter12Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponsePageUserResponse> {
        const response = await this.filter12Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async lockUserAccountRaw(requestParameters: LockUserAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseVoid>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling lockUserAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/users/{userId}/lock`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseVoidFromJSON(jsonValue));
    }

    /**
     */
    async lockUserAccount(requestParameters: LockUserAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseVoid> {
        const response = await this.lockUserAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async unlockUserAccountRaw(requestParameters: UnlockUserAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomApiResponseVoid>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling unlockUserAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/admin/users/{userId}/unlock`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomApiResponseVoidFromJSON(jsonValue));
    }

    /**
     */
    async unlockUserAccount(requestParameters: UnlockUserAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomApiResponseVoid> {
        const response = await this.unlockUserAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
