/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressResponse
 */
export interface AddressResponse {
    /**
     * 
     * @type {string}
     * @memberof AddressResponse
     */
    street?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressResponse
     */
    wardName?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressResponse
     */
    districtName?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressResponse
     */
    city?: string;
}

/**
 * Check if a given object implements the AddressResponse interface.
 */
export function instanceOfAddressResponse(value: object): value is AddressResponse {
    return true;
}

export function AddressResponseFromJSON(json: any): AddressResponse {
    return AddressResponseFromJSONTyped(json, false);
}

export function AddressResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'street': json['street'] == null ? undefined : json['street'],
        'wardName': json['wardName'] == null ? undefined : json['wardName'],
        'districtName': json['districtName'] == null ? undefined : json['districtName'],
        'city': json['city'] == null ? undefined : json['city'],
    };
}

export function AddressResponseToJSON(json: any): AddressResponse {
    return AddressResponseToJSONTyped(json, false);
}

export function AddressResponseToJSONTyped(value?: AddressResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'street': value['street'],
        'wardName': value['wardName'],
        'districtName': value['districtName'],
        'city': value['city'],
    };
}

