/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AllergyRequest
 */
export interface AllergyRequest {
    /**
     * 
     * @type {string}
     * @memberof AllergyRequest
     */
    substance: string;
    /**
     * 
     * @type {string}
     * @memberof AllergyRequest
     */
    reaction: string;
    /**
     * 
     * @type {string}
     * @memberof AllergyRequest
     */
    severity: string;
}

/**
 * Check if a given object implements the AllergyRequest interface.
 */
export function instanceOfAllergyRequest(value: object): value is AllergyRequest {
    if (!('substance' in value) || value['substance'] === undefined) return false;
    if (!('reaction' in value) || value['reaction'] === undefined) return false;
    if (!('severity' in value) || value['severity'] === undefined) return false;
    return true;
}

export function AllergyRequestFromJSON(json: any): AllergyRequest {
    return AllergyRequestFromJSONTyped(json, false);
}

export function AllergyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllergyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'substance': json['substance'],
        'reaction': json['reaction'],
        'severity': json['severity'],
    };
}

export function AllergyRequestToJSON(json: any): AllergyRequest {
    return AllergyRequestToJSONTyped(json, false);
}

export function AllergyRequestToJSONTyped(value?: AllergyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'substance': value['substance'],
        'reaction': value['reaction'],
        'severity': value['severity'],
    };
}

