/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppointmentRequest
 */
export interface AppointmentRequest {
    /**
     * 
     * @type {string}
     * @memberof AppointmentRequest
     */
    patientId?: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRequest
     */
    specialtyId?: string;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRequest
     */
    type?: AppointmentRequestTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRequest
     */
    status?: AppointmentRequestStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRequest
     */
    source?: AppointmentRequestSourceEnum;
    /**
     * 
     * @type {string}
     * @memberof AppointmentRequest
     */
    note?: string;
}


/**
 * @export
 */
export const AppointmentRequestTypeEnum = {
    Consultation: 'CONSULTATION',
    FollowUp: 'FOLLOW_UP',
    Emergency: 'EMERGENCY',
    Online: 'ONLINE'
} as const;
export type AppointmentRequestTypeEnum = typeof AppointmentRequestTypeEnum[keyof typeof AppointmentRequestTypeEnum];

/**
 * @export
 */
export const AppointmentRequestStatusEnum = {
    Pending: 'PENDING',
    Confirmed: 'CONFIRMED',
    CheckedIn: 'CHECKED_IN',
    InProgress: 'IN_PROGRESS',
    Completed: 'COMPLETED',
    Cancelled: 'CANCELLED',
    NoShow: 'NO_SHOW'
} as const;
export type AppointmentRequestStatusEnum = typeof AppointmentRequestStatusEnum[keyof typeof AppointmentRequestStatusEnum];

/**
 * @export
 */
export const AppointmentRequestSourceEnum = {
    System: 'SYSTEM',
    StaffCreated: 'STAFF_CREATED',
    PatientPortal: 'PATIENT_PORTAL',
    MobileApp: 'MOBILE_APP',
    WalkIn: 'WALK_IN'
} as const;
export type AppointmentRequestSourceEnum = typeof AppointmentRequestSourceEnum[keyof typeof AppointmentRequestSourceEnum];


/**
 * Check if a given object implements the AppointmentRequest interface.
 */
export function instanceOfAppointmentRequest(value: object): value is AppointmentRequest {
    return true;
}

export function AppointmentRequestFromJSON(json: any): AppointmentRequest {
    return AppointmentRequestFromJSONTyped(json, false);
}

export function AppointmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppointmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'patientId': json['patientId'] == null ? undefined : json['patientId'],
        'specialtyId': json['specialtyId'] == null ? undefined : json['specialtyId'],
        'type': json['type'] == null ? undefined : json['type'],
        'status': json['status'] == null ? undefined : json['status'],
        'source': json['source'] == null ? undefined : json['source'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function AppointmentRequestToJSON(json: any): AppointmentRequest {
    return AppointmentRequestToJSONTyped(json, false);
}

export function AppointmentRequestToJSONTyped(value?: AppointmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'patientId': value['patientId'],
        'specialtyId': value['specialtyId'],
        'type': value['type'],
        'status': value['status'],
        'source': value['source'],
        'note': value['note'],
    };
}

