/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LargeBlobAuthenticationInput } from './LargeBlobAuthenticationInput';
import {
    LargeBlobAuthenticationInputFromJSON,
    LargeBlobAuthenticationInputFromJSONTyped,
    LargeBlobAuthenticationInputToJSON,
    LargeBlobAuthenticationInputToJSONTyped,
} from './LargeBlobAuthenticationInput';
import type { AppId } from './AppId';
import {
    AppIdFromJSON,
    AppIdFromJSONTyped,
    AppIdToJSON,
    AppIdToJSONTyped,
} from './AppId';
import type { PrfAuthenticationInput } from './PrfAuthenticationInput';
import {
    PrfAuthenticationInputFromJSON,
    PrfAuthenticationInputFromJSONTyped,
    PrfAuthenticationInputToJSON,
    PrfAuthenticationInputToJSONTyped,
} from './PrfAuthenticationInput';

/**
 * 
 * @export
 * @interface AssertionExtensionInputs
 */
export interface AssertionExtensionInputs {
    /**
     * 
     * @type {AppId}
     * @memberof AssertionExtensionInputs
     */
    appid?: AppId;
    /**
     * 
     * @type {LargeBlobAuthenticationInput}
     * @memberof AssertionExtensionInputs
     */
    largeBlob?: LargeBlobAuthenticationInput;
    /**
     * 
     * @type {PrfAuthenticationInput}
     * @memberof AssertionExtensionInputs
     */
    prf?: PrfAuthenticationInput;
    /**
     * 
     * @type {boolean}
     * @memberof AssertionExtensionInputs
     */
    uvm?: boolean;
}

/**
 * Check if a given object implements the AssertionExtensionInputs interface.
 */
export function instanceOfAssertionExtensionInputs(value: object): value is AssertionExtensionInputs {
    return true;
}

export function AssertionExtensionInputsFromJSON(json: any): AssertionExtensionInputs {
    return AssertionExtensionInputsFromJSONTyped(json, false);
}

export function AssertionExtensionInputsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssertionExtensionInputs {
    if (json == null) {
        return json;
    }
    return {
        
        'appid': json['appid'] == null ? undefined : AppIdFromJSON(json['appid']),
        'largeBlob': json['largeBlob'] == null ? undefined : LargeBlobAuthenticationInputFromJSON(json['largeBlob']),
        'prf': json['prf'] == null ? undefined : PrfAuthenticationInputFromJSON(json['prf']),
        'uvm': json['uvm'] == null ? undefined : json['uvm'],
    };
}

export function AssertionExtensionInputsToJSON(json: any): AssertionExtensionInputs {
    return AssertionExtensionInputsToJSONTyped(json, false);
}

export function AssertionExtensionInputsToJSONTyped(value?: AssertionExtensionInputs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'appid': AppIdToJSON(value['appid']),
        'largeBlob': LargeBlobAuthenticationInputToJSON(value['largeBlob']),
        'prf': PrfAuthenticationInputToJSON(value['prf']),
        'uvm': value['uvm'],
    };
}

