/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticatorSelectionCriteria
 */
export interface AuthenticatorSelectionCriteria {
    /**
     * 
     * @type {string}
     * @memberof AuthenticatorSelectionCriteria
     */
    authenticatorAttachment?: AuthenticatorSelectionCriteriaAuthenticatorAttachmentEnum;
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticatorSelectionCriteria
     */
    requireResidentKey?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthenticatorSelectionCriteria
     */
    residentKey?: AuthenticatorSelectionCriteriaResidentKeyEnum;
    /**
     * 
     * @type {string}
     * @memberof AuthenticatorSelectionCriteria
     */
    userVerification?: AuthenticatorSelectionCriteriaUserVerificationEnum;
}


/**
 * @export
 */
export const AuthenticatorSelectionCriteriaAuthenticatorAttachmentEnum = {
    CrossPlatform: 'cross-platform',
    Platform: 'platform'
} as const;
export type AuthenticatorSelectionCriteriaAuthenticatorAttachmentEnum = typeof AuthenticatorSelectionCriteriaAuthenticatorAttachmentEnum[keyof typeof AuthenticatorSelectionCriteriaAuthenticatorAttachmentEnum];

/**
 * @export
 */
export const AuthenticatorSelectionCriteriaResidentKeyEnum = {
    Discouraged: 'discouraged',
    Preferred: 'preferred',
    Required: 'required'
} as const;
export type AuthenticatorSelectionCriteriaResidentKeyEnum = typeof AuthenticatorSelectionCriteriaResidentKeyEnum[keyof typeof AuthenticatorSelectionCriteriaResidentKeyEnum];

/**
 * @export
 */
export const AuthenticatorSelectionCriteriaUserVerificationEnum = {
    Discouraged: 'discouraged',
    Preferred: 'preferred',
    Required: 'required'
} as const;
export type AuthenticatorSelectionCriteriaUserVerificationEnum = typeof AuthenticatorSelectionCriteriaUserVerificationEnum[keyof typeof AuthenticatorSelectionCriteriaUserVerificationEnum];


/**
 * Check if a given object implements the AuthenticatorSelectionCriteria interface.
 */
export function instanceOfAuthenticatorSelectionCriteria(value: object): value is AuthenticatorSelectionCriteria {
    return true;
}

export function AuthenticatorSelectionCriteriaFromJSON(json: any): AuthenticatorSelectionCriteria {
    return AuthenticatorSelectionCriteriaFromJSONTyped(json, false);
}

export function AuthenticatorSelectionCriteriaFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticatorSelectionCriteria {
    if (json == null) {
        return json;
    }
    return {
        
        'authenticatorAttachment': json['authenticatorAttachment'] == null ? undefined : json['authenticatorAttachment'],
        'requireResidentKey': json['requireResidentKey'] == null ? undefined : json['requireResidentKey'],
        'residentKey': json['residentKey'] == null ? undefined : json['residentKey'],
        'userVerification': json['userVerification'] == null ? undefined : json['userVerification'],
    };
}

export function AuthenticatorSelectionCriteriaToJSON(json: any): AuthenticatorSelectionCriteria {
    return AuthenticatorSelectionCriteriaToJSONTyped(json, false);
}

export function AuthenticatorSelectionCriteriaToJSONTyped(value?: AuthenticatorSelectionCriteria | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'authenticatorAttachment': value['authenticatorAttachment'],
        'requireResidentKey': value['requireResidentKey'],
        'residentKey': value['residentKey'],
        'userVerification': value['userVerification'],
    };
}

