/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthResponse
 */
export interface AuthResponse {
    /**
     * 
     * @type {boolean}
     * @memberof AuthResponse
     */
    requires2FA?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthResponse
     */
    mfaTypes?: Array<AuthResponseMfaTypesEnum>;
    /**
     * 
     * @type {string}
     * @memberof AuthResponse
     */
    defaultMfaType?: AuthResponseDefaultMfaTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AuthResponse
     */
    challengeId?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthResponse
     */
    tokenType?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {Date}
     * @memberof AuthResponse
     */
    expiresIn?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof AuthResponse
     */
    trustDevice?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AuthResponse
     */
    rememberMe?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthResponse
     */
    deviceId?: string;
}


/**
 * @export
 */
export const AuthResponseMfaTypesEnum = {
    Totp: 'TOTP',
    Sms: 'SMS',
    Email: 'EMAIL',
    PushNotification: 'PUSH_NOTIFICATION',
    Passkey: 'PASSKEY',
    EmailVerification: 'EMAIL_VERIFICATION'
} as const;
export type AuthResponseMfaTypesEnum = typeof AuthResponseMfaTypesEnum[keyof typeof AuthResponseMfaTypesEnum];

/**
 * @export
 */
export const AuthResponseDefaultMfaTypeEnum = {
    Totp: 'TOTP',
    Sms: 'SMS',
    Email: 'EMAIL',
    PushNotification: 'PUSH_NOTIFICATION',
    Passkey: 'PASSKEY',
    EmailVerification: 'EMAIL_VERIFICATION'
} as const;
export type AuthResponseDefaultMfaTypeEnum = typeof AuthResponseDefaultMfaTypeEnum[keyof typeof AuthResponseDefaultMfaTypeEnum];


/**
 * Check if a given object implements the AuthResponse interface.
 */
export function instanceOfAuthResponse(value: object): value is AuthResponse {
    return true;
}

export function AuthResponseFromJSON(json: any): AuthResponse {
    return AuthResponseFromJSONTyped(json, false);
}

export function AuthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'requires2FA': json['requires2FA'] == null ? undefined : json['requires2FA'],
        'mfaTypes': json['mfaTypes'] == null ? undefined : json['mfaTypes'],
        'defaultMfaType': json['defaultMfaType'] == null ? undefined : json['defaultMfaType'],
        'challengeId': json['challengeId'] == null ? undefined : json['challengeId'],
        'tokenType': json['tokenType'] == null ? undefined : json['tokenType'],
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'expiresIn': json['expiresIn'] == null ? undefined : (new Date(json['expiresIn'])),
        'trustDevice': json['trustDevice'] == null ? undefined : json['trustDevice'],
        'rememberMe': json['rememberMe'] == null ? undefined : json['rememberMe'],
        'deviceId': json['deviceId'] == null ? undefined : json['deviceId'],
    };
}

export function AuthResponseToJSON(json: any): AuthResponse {
    return AuthResponseToJSONTyped(json, false);
}

export function AuthResponseToJSONTyped(value?: AuthResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requires2FA': value['requires2FA'],
        'mfaTypes': value['mfaTypes'],
        'defaultMfaType': value['defaultMfaType'],
        'challengeId': value['challengeId'],
        'tokenType': value['tokenType'],
        'accessToken': value['accessToken'],
        'expiresIn': value['expiresIn'] == null ? value['expiresIn'] : value['expiresIn'].toISOString(),
        'trustDevice': value['trustDevice'],
        'rememberMe': value['rememberMe'],
        'deviceId': value['deviceId'],
    };
}

