/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DepartmentSimpleResponse } from './DepartmentSimpleResponse';
import {
    DepartmentSimpleResponseFromJSON,
    DepartmentSimpleResponseFromJSONTyped,
    DepartmentSimpleResponseToJSON,
    DepartmentSimpleResponseToJSONTyped,
} from './DepartmentSimpleResponse';
import type { AddressResponse } from './AddressResponse';
import {
    AddressResponseFromJSON,
    AddressResponseFromJSONTyped,
    AddressResponseToJSON,
    AddressResponseToJSONTyped,
} from './AddressResponse';

/**
 * 
 * @export
 * @interface ClinicResponse
 */
export interface ClinicResponse {
    /**
     * 
     * @type {string}
     * @memberof ClinicResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ClinicResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ClinicResponse
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ClinicResponse
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof ClinicResponse
     */
    email?: string;
    /**
     * 
     * @type {AddressResponse}
     * @memberof ClinicResponse
     */
    address?: AddressResponse;
    /**
     * 
     * @type {Array<DepartmentSimpleResponse>}
     * @memberof ClinicResponse
     */
    departments?: Array<DepartmentSimpleResponse>;
    /**
     * 
     * @type {string}
     * @memberof ClinicResponse
     */
    taxCode?: string;
    /**
     * 
     * @type {string}
     * @memberof ClinicResponse
     */
    website?: string;
    /**
     * 
     * @type {string}
     * @memberof ClinicResponse
     */
    accountNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof ClinicResponse
     */
    bankName?: string;
}

/**
 * Check if a given object implements the ClinicResponse interface.
 */
export function instanceOfClinicResponse(value: object): value is ClinicResponse {
    return true;
}

export function ClinicResponseFromJSON(json: any): ClinicResponse {
    return ClinicResponseFromJSONTyped(json, false);
}

export function ClinicResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClinicResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'email': json['email'] == null ? undefined : json['email'],
        'address': json['address'] == null ? undefined : AddressResponseFromJSON(json['address']),
        'departments': json['departments'] == null ? undefined : ((json['departments'] as Array<any>).map(DepartmentSimpleResponseFromJSON)),
        'taxCode': json['taxCode'] == null ? undefined : json['taxCode'],
        'website': json['website'] == null ? undefined : json['website'],
        'accountNumber': json['accountNumber'] == null ? undefined : json['accountNumber'],
        'bankName': json['bankName'] == null ? undefined : json['bankName'],
    };
}

export function ClinicResponseToJSON(json: any): ClinicResponse {
    return ClinicResponseToJSONTyped(json, false);
}

export function ClinicResponseToJSONTyped(value?: ClinicResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'phone': value['phone'],
        'email': value['email'],
        'address': AddressResponseToJSON(value['address']),
        'departments': value['departments'] == null ? undefined : ((value['departments'] as Array<any>).map(DepartmentSimpleResponseToJSON)),
        'taxCode': value['taxCode'],
        'website': value['website'],
        'accountNumber': value['accountNumber'],
        'bankName': value['bankName'],
    };
}

