/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentRequest
 */
export interface ContentRequest {
    /**
     * 
     * @type {string}
     * @memberof ContentRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentRequest
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentRequest
     */
    body?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentRequest
     */
    excerpt?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentRequest
     */
    coverImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentRequest
     */
    status?: ContentRequestStatusEnum;
    /**
     * 
     * @type {Set<string>}
     * @memberof ContentRequest
     */
    tags?: Set<string>;
}


/**
 * @export
 */
export const ContentRequestStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED',
    Archived: 'ARCHIVED'
} as const;
export type ContentRequestStatusEnum = typeof ContentRequestStatusEnum[keyof typeof ContentRequestStatusEnum];


/**
 * Check if a given object implements the ContentRequest interface.
 */
export function instanceOfContentRequest(value: object): value is ContentRequest {
    return true;
}

export function ContentRequestFromJSON(json: any): ContentRequest {
    return ContentRequestFromJSONTyped(json, false);
}

export function ContentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'body': json['body'] == null ? undefined : json['body'],
        'excerpt': json['excerpt'] == null ? undefined : json['excerpt'],
        'coverImageUrl': json['coverImageUrl'] == null ? undefined : json['coverImageUrl'],
        'status': json['status'] == null ? undefined : json['status'],
        'tags': json['tags'] == null ? undefined : new Set(json['tags']),
    };
}

export function ContentRequestToJSON(json: any): ContentRequest {
    return ContentRequestToJSONTyped(json, false);
}

export function ContentRequestToJSONTyped(value?: ContentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'slug': value['slug'],
        'body': value['body'],
        'excerpt': value['excerpt'],
        'coverImageUrl': value['coverImageUrl'],
        'status': value['status'],
        'tags': value['tags'] == null ? undefined : Array.from(value['tags'] as Set<any>),
    };
}

