/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StaffResponse } from './StaffResponse';
import {
    StaffResponseFromJSON,
    StaffResponseFromJSONTyped,
    StaffResponseToJSON,
    StaffResponseToJSONTyped,
} from './StaffResponse';

/**
 * 
 * @export
 * @interface ContentResponse
 */
export interface ContentResponse {
    /**
     * 
     * @type {string}
     * @memberof ContentResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentResponse
     */
    createdBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof ContentResponse
     */
    createdDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ContentResponse
     */
    lastModifiedBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof ContentResponse
     */
    lastModifiedDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ContentResponse
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentResponse
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentResponse
     */
    body?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentResponse
     */
    excerpt?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentResponse
     */
    coverImageUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentResponse
     */
    status?: ContentResponseStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof ContentResponse
     */
    publishedAt?: Date;
    /**
     * 
     * @type {Set<string>}
     * @memberof ContentResponse
     */
    tags?: Set<string>;
    /**
     * 
     * @type {StaffResponse}
     * @memberof ContentResponse
     */
    author?: StaffResponse;
}


/**
 * @export
 */
export const ContentResponseStatusEnum = {
    Draft: 'DRAFT',
    Published: 'PUBLISHED',
    Archived: 'ARCHIVED'
} as const;
export type ContentResponseStatusEnum = typeof ContentResponseStatusEnum[keyof typeof ContentResponseStatusEnum];


/**
 * Check if a given object implements the ContentResponse interface.
 */
export function instanceOfContentResponse(value: object): value is ContentResponse {
    return true;
}

export function ContentResponseFromJSON(json: any): ContentResponse {
    return ContentResponseFromJSONTyped(json, false);
}

export function ContentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'createdDate': json['createdDate'] == null ? undefined : (new Date(json['createdDate'])),
        'lastModifiedBy': json['lastModifiedBy'] == null ? undefined : json['lastModifiedBy'],
        'lastModifiedDate': json['lastModifiedDate'] == null ? undefined : (new Date(json['lastModifiedDate'])),
        'title': json['title'] == null ? undefined : json['title'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'body': json['body'] == null ? undefined : json['body'],
        'excerpt': json['excerpt'] == null ? undefined : json['excerpt'],
        'coverImageUrl': json['coverImageUrl'] == null ? undefined : json['coverImageUrl'],
        'status': json['status'] == null ? undefined : json['status'],
        'publishedAt': json['publishedAt'] == null ? undefined : (new Date(json['publishedAt'])),
        'tags': json['tags'] == null ? undefined : new Set(json['tags']),
        'author': json['author'] == null ? undefined : StaffResponseFromJSON(json['author']),
    };
}

export function ContentResponseToJSON(json: any): ContentResponse {
    return ContentResponseToJSONTyped(json, false);
}

export function ContentResponseToJSONTyped(value?: ContentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdBy': value['createdBy'],
        'createdDate': value['createdDate'] == null ? value['createdDate'] : value['createdDate'].toISOString(),
        'lastModifiedBy': value['lastModifiedBy'],
        'lastModifiedDate': value['lastModifiedDate'] == null ? value['lastModifiedDate'] : value['lastModifiedDate'].toISOString(),
        'title': value['title'],
        'slug': value['slug'],
        'body': value['body'],
        'excerpt': value['excerpt'],
        'coverImageUrl': value['coverImageUrl'],
        'status': value['status'],
        'publishedAt': value['publishedAt'] == null ? value['publishedAt'] : value['publishedAt'].toISOString(),
        'tags': value['tags'] == null ? undefined : Array.from(value['tags'] as Set<any>),
        'author': StaffResponseToJSON(value['author']),
    };
}

