/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateServiceOrderRequest
 */
export interface CreateServiceOrderRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateServiceOrderRequest
     */
    serviceIds?: Array<string>;
}

/**
 * Check if a given object implements the CreateServiceOrderRequest interface.
 */
export function instanceOfCreateServiceOrderRequest(value: object): value is CreateServiceOrderRequest {
    return true;
}

export function CreateServiceOrderRequestFromJSON(json: any): CreateServiceOrderRequest {
    return CreateServiceOrderRequestFromJSONTyped(json, false);
}

export function CreateServiceOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateServiceOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceIds': json['serviceIds'] == null ? undefined : json['serviceIds'],
    };
}

export function CreateServiceOrderRequestToJSON(json: any): CreateServiceOrderRequest {
    return CreateServiceOrderRequestToJSONTyped(json, false);
}

export function CreateServiceOrderRequestToJSONTyped(value?: CreateServiceOrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serviceIds': value['serviceIds'],
    };
}

