/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomApiResponseMapStringLong
 */
export interface CustomApiResponseMapStringLong {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseMapStringLong
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseMapStringLong
     */
    message?: string;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof CustomApiResponseMapStringLong
     */
    data?: { [key: string]: number; };
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseMapStringLong
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseMapStringLong
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseMapStringLong interface.
 */
export function instanceOfCustomApiResponseMapStringLong(value: object): value is CustomApiResponseMapStringLong {
    return true;
}

export function CustomApiResponseMapStringLongFromJSON(json: any): CustomApiResponseMapStringLong {
    return CustomApiResponseMapStringLongFromJSONTyped(json, false);
}

export function CustomApiResponseMapStringLongFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseMapStringLong {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : json['data'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseMapStringLongToJSON(json: any): CustomApiResponseMapStringLong {
    return CustomApiResponseMapStringLongToJSONTyped(json, false);
}

export function CustomApiResponseMapStringLongToJSONTyped(value?: CustomApiResponseMapStringLong | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': value['data'],
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

