/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StaffResponse } from './StaffResponse';
import {
    StaffResponseFromJSON,
    StaffResponseFromJSONTyped,
    StaffResponseToJSON,
    StaffResponseToJSONTyped,
} from './StaffResponse';

/**
 * 
 * @export
 * @interface CustomApiResponseStaffResponse
 */
export interface CustomApiResponseStaffResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseStaffResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseStaffResponse
     */
    message?: string;
    /**
     * 
     * @type {StaffResponse}
     * @memberof CustomApiResponseStaffResponse
     */
    data?: StaffResponse;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseStaffResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseStaffResponse
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseStaffResponse interface.
 */
export function instanceOfCustomApiResponseStaffResponse(value: object): value is CustomApiResponseStaffResponse {
    return true;
}

export function CustomApiResponseStaffResponseFromJSON(json: any): CustomApiResponseStaffResponse {
    return CustomApiResponseStaffResponseFromJSONTyped(json, false);
}

export function CustomApiResponseStaffResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseStaffResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : StaffResponseFromJSON(json['data']),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseStaffResponseToJSON(json: any): CustomApiResponseStaffResponse {
    return CustomApiResponseStaffResponseToJSONTyped(json, false);
}

export function CustomApiResponseStaffResponseToJSONTyped(value?: CustomApiResponseStaffResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': StaffResponseToJSON(value['data']),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

