/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MfaConfigResponse } from './MfaConfigResponse';
import {
    MfaConfigResponseFromJSON,
    MfaConfigResponseFromJSONTyped,
    MfaConfigResponseToJSON,
    MfaConfigResponseToJSONTyped,
} from './MfaConfigResponse';

/**
 * 
 * @export
 * @interface CustomApiResponseListMfaConfigResponse
 */
export interface CustomApiResponseListMfaConfigResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseListMfaConfigResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseListMfaConfigResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<MfaConfigResponse>}
     * @memberof CustomApiResponseListMfaConfigResponse
     */
    data?: Array<MfaConfigResponse>;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseListMfaConfigResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseListMfaConfigResponse
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseListMfaConfigResponse interface.
 */
export function instanceOfCustomApiResponseListMfaConfigResponse(value: object): value is CustomApiResponseListMfaConfigResponse {
    return true;
}

export function CustomApiResponseListMfaConfigResponseFromJSON(json: any): CustomApiResponseListMfaConfigResponse {
    return CustomApiResponseListMfaConfigResponseFromJSONTyped(json, false);
}

export function CustomApiResponseListMfaConfigResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseListMfaConfigResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(MfaConfigResponseFromJSON)),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseListMfaConfigResponseToJSON(json: any): CustomApiResponseListMfaConfigResponse {
    return CustomApiResponseListMfaConfigResponseToJSONTyped(json, false);
}

export function CustomApiResponseListMfaConfigResponseToJSONTyped(value?: CustomApiResponseListMfaConfigResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(MfaConfigResponseToJSON)),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

