/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueueTicketResponse } from './QueueTicketResponse';
import {
    QueueTicketResponseFromJSON,
    QueueTicketResponseFromJSONTyped,
    QueueTicketResponseToJSON,
    QueueTicketResponseToJSONTyped,
} from './QueueTicketResponse';

/**
 * 
 * @export
 * @interface CustomApiResponseQueueTicketResponse
 */
export interface CustomApiResponseQueueTicketResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseQueueTicketResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseQueueTicketResponse
     */
    message?: string;
    /**
     * 
     * @type {QueueTicketResponse}
     * @memberof CustomApiResponseQueueTicketResponse
     */
    data?: QueueTicketResponse;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseQueueTicketResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseQueueTicketResponse
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseQueueTicketResponse interface.
 */
export function instanceOfCustomApiResponseQueueTicketResponse(value: object): value is CustomApiResponseQueueTicketResponse {
    return true;
}

export function CustomApiResponseQueueTicketResponseFromJSON(json: any): CustomApiResponseQueueTicketResponse {
    return CustomApiResponseQueueTicketResponseFromJSONTyped(json, false);
}

export function CustomApiResponseQueueTicketResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseQueueTicketResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : QueueTicketResponseFromJSON(json['data']),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseQueueTicketResponseToJSON(json: any): CustomApiResponseQueueTicketResponse {
    return CustomApiResponseQueueTicketResponseToJSONTyped(json, false);
}

export function CustomApiResponseQueueTicketResponseToJSONTyped(value?: CustomApiResponseQueueTicketResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': QueueTicketResponseToJSON(value['data']),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

