/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EmergencyContactResponse } from './EmergencyContactResponse';
import {
    EmergencyContactResponseFromJSON,
    EmergencyContactResponseFromJSONTyped,
    EmergencyContactResponseToJSON,
    EmergencyContactResponseToJSONTyped,
} from './EmergencyContactResponse';

/**
 * 
 * @export
 * @interface CustomApiResponseEmergencyContactResponse
 */
export interface CustomApiResponseEmergencyContactResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseEmergencyContactResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseEmergencyContactResponse
     */
    message?: string;
    /**
     * 
     * @type {EmergencyContactResponse}
     * @memberof CustomApiResponseEmergencyContactResponse
     */
    data?: EmergencyContactResponse;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseEmergencyContactResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseEmergencyContactResponse
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseEmergencyContactResponse interface.
 */
export function instanceOfCustomApiResponseEmergencyContactResponse(value: object): value is CustomApiResponseEmergencyContactResponse {
    return true;
}

export function CustomApiResponseEmergencyContactResponseFromJSON(json: any): CustomApiResponseEmergencyContactResponse {
    return CustomApiResponseEmergencyContactResponseFromJSONTyped(json, false);
}

export function CustomApiResponseEmergencyContactResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseEmergencyContactResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : EmergencyContactResponseFromJSON(json['data']),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseEmergencyContactResponseToJSON(json: any): CustomApiResponseEmergencyContactResponse {
    return CustomApiResponseEmergencyContactResponseToJSONTyped(json, false);
}

export function CustomApiResponseEmergencyContactResponseToJSONTyped(value?: CustomApiResponseEmergencyContactResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': EmergencyContactResponseToJSON(value['data']),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

