/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthResponse } from './AuthResponse';
import {
    AuthResponseFromJSON,
    AuthResponseFromJSONTyped,
    AuthResponseToJSON,
    AuthResponseToJSONTyped,
} from './AuthResponse';

/**
 * 
 * @export
 * @interface CustomApiResponseAuthResponse
 */
export interface CustomApiResponseAuthResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseAuthResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseAuthResponse
     */
    message?: string;
    /**
     * 
     * @type {AuthResponse}
     * @memberof CustomApiResponseAuthResponse
     */
    data?: AuthResponse;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseAuthResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseAuthResponse
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseAuthResponse interface.
 */
export function instanceOfCustomApiResponseAuthResponse(value: object): value is CustomApiResponseAuthResponse {
    return true;
}

export function CustomApiResponseAuthResponseFromJSON(json: any): CustomApiResponseAuthResponse {
    return CustomApiResponseAuthResponseFromJSONTyped(json, false);
}

export function CustomApiResponseAuthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseAuthResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : AuthResponseFromJSON(json['data']),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseAuthResponseToJSON(json: any): CustomApiResponseAuthResponse {
    return CustomApiResponseAuthResponseToJSONTyped(json, false);
}

export function CustomApiResponseAuthResponseToJSONTyped(value?: CustomApiResponseAuthResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': AuthResponseToJSON(value['data']),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

