/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StaffWorkloadResponse } from './StaffWorkloadResponse';
import {
    StaffWorkloadResponseFromJSON,
    StaffWorkloadResponseFromJSONTyped,
    StaffWorkloadResponseToJSON,
    StaffWorkloadResponseToJSONTyped,
} from './StaffWorkloadResponse';

/**
 * 
 * @export
 * @interface CustomApiResponseListStaffWorkloadResponse
 */
export interface CustomApiResponseListStaffWorkloadResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseListStaffWorkloadResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseListStaffWorkloadResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<StaffWorkloadResponse>}
     * @memberof CustomApiResponseListStaffWorkloadResponse
     */
    data?: Array<StaffWorkloadResponse>;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseListStaffWorkloadResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseListStaffWorkloadResponse
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseListStaffWorkloadResponse interface.
 */
export function instanceOfCustomApiResponseListStaffWorkloadResponse(value: object): value is CustomApiResponseListStaffWorkloadResponse {
    return true;
}

export function CustomApiResponseListStaffWorkloadResponseFromJSON(json: any): CustomApiResponseListStaffWorkloadResponse {
    return CustomApiResponseListStaffWorkloadResponseFromJSONTyped(json, false);
}

export function CustomApiResponseListStaffWorkloadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseListStaffWorkloadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(StaffWorkloadResponseFromJSON)),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseListStaffWorkloadResponseToJSON(json: any): CustomApiResponseListStaffWorkloadResponse {
    return CustomApiResponseListStaffWorkloadResponseToJSONTyped(json, false);
}

export function CustomApiResponseListStaffWorkloadResponseToJSONTyped(value?: CustomApiResponseListStaffWorkloadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(StaffWorkloadResponseToJSON)),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

