/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountSettingResponse } from './AccountSettingResponse';
import {
    AccountSettingResponseFromJSON,
    AccountSettingResponseFromJSONTyped,
    AccountSettingResponseToJSON,
    AccountSettingResponseToJSONTyped,
} from './AccountSettingResponse';

/**
 * 
 * @export
 * @interface CustomApiResponseAccountSettingResponse
 */
export interface CustomApiResponseAccountSettingResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseAccountSettingResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseAccountSettingResponse
     */
    message?: string;
    /**
     * 
     * @type {AccountSettingResponse}
     * @memberof CustomApiResponseAccountSettingResponse
     */
    data?: AccountSettingResponse;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseAccountSettingResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseAccountSettingResponse
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseAccountSettingResponse interface.
 */
export function instanceOfCustomApiResponseAccountSettingResponse(value: object): value is CustomApiResponseAccountSettingResponse {
    return true;
}

export function CustomApiResponseAccountSettingResponseFromJSON(json: any): CustomApiResponseAccountSettingResponse {
    return CustomApiResponseAccountSettingResponseFromJSONTyped(json, false);
}

export function CustomApiResponseAccountSettingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseAccountSettingResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : AccountSettingResponseFromJSON(json['data']),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseAccountSettingResponseToJSON(json: any): CustomApiResponseAccountSettingResponse {
    return CustomApiResponseAccountSettingResponseToJSONTyped(json, false);
}

export function CustomApiResponseAccountSettingResponseToJSONTyped(value?: CustomApiResponseAccountSettingResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': AccountSettingResponseToJSON(value['data']),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

