/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MfaInitResponse } from './MfaInitResponse';
import {
    MfaInitResponseFromJSON,
    MfaInitResponseFromJSONTyped,
    MfaInitResponseToJSON,
    MfaInitResponseToJSONTyped,
} from './MfaInitResponse';

/**
 * 
 * @export
 * @interface CustomApiResponseMfaInitResponse
 */
export interface CustomApiResponseMfaInitResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseMfaInitResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseMfaInitResponse
     */
    message?: string;
    /**
     * 
     * @type {MfaInitResponse}
     * @memberof CustomApiResponseMfaInitResponse
     */
    data?: MfaInitResponse;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseMfaInitResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseMfaInitResponse
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseMfaInitResponse interface.
 */
export function instanceOfCustomApiResponseMfaInitResponse(value: object): value is CustomApiResponseMfaInitResponse {
    return true;
}

export function CustomApiResponseMfaInitResponseFromJSON(json: any): CustomApiResponseMfaInitResponse {
    return CustomApiResponseMfaInitResponseFromJSONTyped(json, false);
}

export function CustomApiResponseMfaInitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseMfaInitResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : MfaInitResponseFromJSON(json['data']),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseMfaInitResponseToJSON(json: any): CustomApiResponseMfaInitResponse {
    return CustomApiResponseMfaInitResponseToJSONTyped(json, false);
}

export function CustomApiResponseMfaInitResponseToJSONTyped(value?: CustomApiResponseMfaInitResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': MfaInitResponseToJSON(value['data']),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

