/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceOrderResponse } from './ServiceOrderResponse';
import {
    ServiceOrderResponseFromJSON,
    ServiceOrderResponseFromJSONTyped,
    ServiceOrderResponseToJSON,
    ServiceOrderResponseToJSONTyped,
} from './ServiceOrderResponse';

/**
 * 
 * @export
 * @interface CustomApiResponseListServiceOrderResponse
 */
export interface CustomApiResponseListServiceOrderResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseListServiceOrderResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseListServiceOrderResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<ServiceOrderResponse>}
     * @memberof CustomApiResponseListServiceOrderResponse
     */
    data?: Array<ServiceOrderResponse>;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseListServiceOrderResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseListServiceOrderResponse
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseListServiceOrderResponse interface.
 */
export function instanceOfCustomApiResponseListServiceOrderResponse(value: object): value is CustomApiResponseListServiceOrderResponse {
    return true;
}

export function CustomApiResponseListServiceOrderResponseFromJSON(json: any): CustomApiResponseListServiceOrderResponse {
    return CustomApiResponseListServiceOrderResponseFromJSONTyped(json, false);
}

export function CustomApiResponseListServiceOrderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseListServiceOrderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ServiceOrderResponseFromJSON)),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseListServiceOrderResponseToJSON(json: any): CustomApiResponseListServiceOrderResponse {
    return CustomApiResponseListServiceOrderResponseToJSONTyped(json, false);
}

export function CustomApiResponseListServiceOrderResponseToJSONTyped(value?: CustomApiResponseListServiceOrderResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ServiceOrderResponseToJSON)),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

