/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageObject } from './PageObject';
import {
    PageObjectFromJSON,
    PageObjectFromJSONTyped,
    PageObjectToJSON,
    PageObjectToJSONTyped,
} from './PageObject';

/**
 * 
 * @export
 * @interface CustomApiResponsePageStaffResponse
 */
export interface CustomApiResponsePageStaffResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponsePageStaffResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponsePageStaffResponse
     */
    message?: string;
    /**
     * 
     * @type {PageObject}
     * @memberof CustomApiResponsePageStaffResponse
     */
    data?: PageObject;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponsePageStaffResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponsePageStaffResponse
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponsePageStaffResponse interface.
 */
export function instanceOfCustomApiResponsePageStaffResponse(value: object): value is CustomApiResponsePageStaffResponse {
    return true;
}

export function CustomApiResponsePageStaffResponseFromJSON(json: any): CustomApiResponsePageStaffResponse {
    return CustomApiResponsePageStaffResponseFromJSONTyped(json, false);
}

export function CustomApiResponsePageStaffResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponsePageStaffResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : PageObjectFromJSON(json['data']),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponsePageStaffResponseToJSON(json: any): CustomApiResponsePageStaffResponse {
    return CustomApiResponsePageStaffResponseToJSONTyped(json, false);
}

export function CustomApiResponsePageStaffResponseToJSONTyped(value?: CustomApiResponsePageStaffResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': PageObjectToJSON(value['data']),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

