/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageObject } from './PageObject';
import {
    PageObjectFromJSON,
    PageObjectFromJSONTyped,
    PageObjectToJSON,
    PageObjectToJSONTyped,
} from './PageObject';

/**
 * 
 * @export
 * @interface CustomApiResponsePageExaminationResponse
 */
export interface CustomApiResponsePageExaminationResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponsePageExaminationResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponsePageExaminationResponse
     */
    message?: string;
    /**
     * 
     * @type {PageObject}
     * @memberof CustomApiResponsePageExaminationResponse
     */
    data?: PageObject;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponsePageExaminationResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponsePageExaminationResponse
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponsePageExaminationResponse interface.
 */
export function instanceOfCustomApiResponsePageExaminationResponse(value: object): value is CustomApiResponsePageExaminationResponse {
    return true;
}

export function CustomApiResponsePageExaminationResponseFromJSON(json: any): CustomApiResponsePageExaminationResponse {
    return CustomApiResponsePageExaminationResponseFromJSONTyped(json, false);
}

export function CustomApiResponsePageExaminationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponsePageExaminationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : PageObjectFromJSON(json['data']),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponsePageExaminationResponseToJSON(json: any): CustomApiResponsePageExaminationResponse {
    return CustomApiResponsePageExaminationResponseToJSONTyped(json, false);
}

export function CustomApiResponsePageExaminationResponseToJSONTyped(value?: CustomApiResponsePageExaminationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': PageObjectToJSON(value['data']),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

