/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomApiResponseBoolean
 */
export interface CustomApiResponseBoolean {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseBoolean
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseBoolean
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CustomApiResponseBoolean
     */
    data?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseBoolean
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseBoolean
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseBoolean interface.
 */
export function instanceOfCustomApiResponseBoolean(value: object): value is CustomApiResponseBoolean {
    return true;
}

export function CustomApiResponseBooleanFromJSON(json: any): CustomApiResponseBoolean {
    return CustomApiResponseBooleanFromJSONTyped(json, false);
}

export function CustomApiResponseBooleanFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseBoolean {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : json['data'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseBooleanToJSON(json: any): CustomApiResponseBoolean {
    return CustomApiResponseBooleanToJSONTyped(json, false);
}

export function CustomApiResponseBooleanToJSONTyped(value?: CustomApiResponseBoolean | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': value['data'],
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

