/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LabOrderResponse } from './LabOrderResponse';
import {
    LabOrderResponseFromJSON,
    LabOrderResponseFromJSONTyped,
    LabOrderResponseToJSON,
    LabOrderResponseToJSONTyped,
} from './LabOrderResponse';

/**
 * 
 * @export
 * @interface CustomApiResponseListLabOrderResponse
 */
export interface CustomApiResponseListLabOrderResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseListLabOrderResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseListLabOrderResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<LabOrderResponse>}
     * @memberof CustomApiResponseListLabOrderResponse
     */
    data?: Array<LabOrderResponse>;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseListLabOrderResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseListLabOrderResponse
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseListLabOrderResponse interface.
 */
export function instanceOfCustomApiResponseListLabOrderResponse(value: object): value is CustomApiResponseListLabOrderResponse {
    return true;
}

export function CustomApiResponseListLabOrderResponseFromJSON(json: any): CustomApiResponseListLabOrderResponse {
    return CustomApiResponseListLabOrderResponseFromJSONTyped(json, false);
}

export function CustomApiResponseListLabOrderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseListLabOrderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(LabOrderResponseFromJSON)),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseListLabOrderResponseToJSON(json: any): CustomApiResponseListLabOrderResponse {
    return CustomApiResponseListLabOrderResponseToJSONTyped(json, false);
}

export function CustomApiResponseListLabOrderResponseToJSONTyped(value?: CustomApiResponseListLabOrderResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(LabOrderResponseToJSON)),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

