/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DiagnosisResponse } from './DiagnosisResponse';
import {
    DiagnosisResponseFromJSON,
    DiagnosisResponseFromJSONTyped,
    DiagnosisResponseToJSON,
    DiagnosisResponseToJSONTyped,
} from './DiagnosisResponse';

/**
 * 
 * @export
 * @interface CustomApiResponseDiagnosisResponse
 */
export interface CustomApiResponseDiagnosisResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseDiagnosisResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseDiagnosisResponse
     */
    message?: string;
    /**
     * 
     * @type {DiagnosisResponse}
     * @memberof CustomApiResponseDiagnosisResponse
     */
    data?: DiagnosisResponse;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseDiagnosisResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseDiagnosisResponse
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseDiagnosisResponse interface.
 */
export function instanceOfCustomApiResponseDiagnosisResponse(value: object): value is CustomApiResponseDiagnosisResponse {
    return true;
}

export function CustomApiResponseDiagnosisResponseFromJSON(json: any): CustomApiResponseDiagnosisResponse {
    return CustomApiResponseDiagnosisResponseFromJSONTyped(json, false);
}

export function CustomApiResponseDiagnosisResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseDiagnosisResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : DiagnosisResponseFromJSON(json['data']),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseDiagnosisResponseToJSON(json: any): CustomApiResponseDiagnosisResponse {
    return CustomApiResponseDiagnosisResponseToJSONTyped(json, false);
}

export function CustomApiResponseDiagnosisResponseToJSONTyped(value?: CustomApiResponseDiagnosisResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': DiagnosisResponseToJSON(value['data']),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

