/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceCatalogResponse } from './ServiceCatalogResponse';
import {
    ServiceCatalogResponseFromJSON,
    ServiceCatalogResponseFromJSONTyped,
    ServiceCatalogResponseToJSON,
    ServiceCatalogResponseToJSONTyped,
} from './ServiceCatalogResponse';

/**
 * 
 * @export
 * @interface CustomApiResponseServiceCatalogResponse
 */
export interface CustomApiResponseServiceCatalogResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseServiceCatalogResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseServiceCatalogResponse
     */
    message?: string;
    /**
     * 
     * @type {ServiceCatalogResponse}
     * @memberof CustomApiResponseServiceCatalogResponse
     */
    data?: ServiceCatalogResponse;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseServiceCatalogResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseServiceCatalogResponse
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseServiceCatalogResponse interface.
 */
export function instanceOfCustomApiResponseServiceCatalogResponse(value: object): value is CustomApiResponseServiceCatalogResponse {
    return true;
}

export function CustomApiResponseServiceCatalogResponseFromJSON(json: any): CustomApiResponseServiceCatalogResponse {
    return CustomApiResponseServiceCatalogResponseFromJSONTyped(json, false);
}

export function CustomApiResponseServiceCatalogResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseServiceCatalogResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ServiceCatalogResponseFromJSON(json['data']),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseServiceCatalogResponseToJSON(json: any): CustomApiResponseServiceCatalogResponse {
    return CustomApiResponseServiceCatalogResponseToJSONTyped(json, false);
}

export function CustomApiResponseServiceCatalogResponseToJSONTyped(value?: CustomApiResponseServiceCatalogResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': ServiceCatalogResponseToJSON(value['data']),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

