/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppointmentResponse } from './AppointmentResponse';
import {
    AppointmentResponseFromJSON,
    AppointmentResponseFromJSONTyped,
    AppointmentResponseToJSON,
    AppointmentResponseToJSONTyped,
} from './AppointmentResponse';

/**
 * 
 * @export
 * @interface CustomApiResponseAppointmentResponse
 */
export interface CustomApiResponseAppointmentResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseAppointmentResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseAppointmentResponse
     */
    message?: string;
    /**
     * 
     * @type {AppointmentResponse}
     * @memberof CustomApiResponseAppointmentResponse
     */
    data?: AppointmentResponse;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseAppointmentResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseAppointmentResponse
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseAppointmentResponse interface.
 */
export function instanceOfCustomApiResponseAppointmentResponse(value: object): value is CustomApiResponseAppointmentResponse {
    return true;
}

export function CustomApiResponseAppointmentResponseFromJSON(json: any): CustomApiResponseAppointmentResponse {
    return CustomApiResponseAppointmentResponseFromJSONTyped(json, false);
}

export function CustomApiResponseAppointmentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseAppointmentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : AppointmentResponseFromJSON(json['data']),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseAppointmentResponseToJSON(json: any): CustomApiResponseAppointmentResponse {
    return CustomApiResponseAppointmentResponseToJSONTyped(json, false);
}

export function CustomApiResponseAppointmentResponseToJSONTyped(value?: CustomApiResponseAppointmentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': AppointmentResponseToJSON(value['data']),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

