/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SpecialtyDistributionResponse } from './SpecialtyDistributionResponse';
import {
    SpecialtyDistributionResponseFromJSON,
    SpecialtyDistributionResponseFromJSONTyped,
    SpecialtyDistributionResponseToJSON,
    SpecialtyDistributionResponseToJSONTyped,
} from './SpecialtyDistributionResponse';

/**
 * 
 * @export
 * @interface CustomApiResponseListSpecialtyDistributionResponse
 */
export interface CustomApiResponseListSpecialtyDistributionResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseListSpecialtyDistributionResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseListSpecialtyDistributionResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<SpecialtyDistributionResponse>}
     * @memberof CustomApiResponseListSpecialtyDistributionResponse
     */
    data?: Array<SpecialtyDistributionResponse>;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseListSpecialtyDistributionResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseListSpecialtyDistributionResponse
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseListSpecialtyDistributionResponse interface.
 */
export function instanceOfCustomApiResponseListSpecialtyDistributionResponse(value: object): value is CustomApiResponseListSpecialtyDistributionResponse {
    return true;
}

export function CustomApiResponseListSpecialtyDistributionResponseFromJSON(json: any): CustomApiResponseListSpecialtyDistributionResponse {
    return CustomApiResponseListSpecialtyDistributionResponseFromJSONTyped(json, false);
}

export function CustomApiResponseListSpecialtyDistributionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseListSpecialtyDistributionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(SpecialtyDistributionResponseFromJSON)),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseListSpecialtyDistributionResponseToJSON(json: any): CustomApiResponseListSpecialtyDistributionResponse {
    return CustomApiResponseListSpecialtyDistributionResponseToJSONTyped(json, false);
}

export function CustomApiResponseListSpecialtyDistributionResponseToJSONTyped(value?: CustomApiResponseListSpecialtyDistributionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(SpecialtyDistributionResponseToJSON)),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

