/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceCatalogResponse } from './ServiceCatalogResponse';
import {
    ServiceCatalogResponseFromJSON,
    ServiceCatalogResponseFromJSONTyped,
    ServiceCatalogResponseToJSON,
    ServiceCatalogResponseToJSONTyped,
} from './ServiceCatalogResponse';

/**
 * 
 * @export
 * @interface CustomApiResponseListServiceCatalogResponse
 */
export interface CustomApiResponseListServiceCatalogResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseListServiceCatalogResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseListServiceCatalogResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<ServiceCatalogResponse>}
     * @memberof CustomApiResponseListServiceCatalogResponse
     */
    data?: Array<ServiceCatalogResponse>;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseListServiceCatalogResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseListServiceCatalogResponse
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseListServiceCatalogResponse interface.
 */
export function instanceOfCustomApiResponseListServiceCatalogResponse(value: object): value is CustomApiResponseListServiceCatalogResponse {
    return true;
}

export function CustomApiResponseListServiceCatalogResponseFromJSON(json: any): CustomApiResponseListServiceCatalogResponse {
    return CustomApiResponseListServiceCatalogResponseFromJSONTyped(json, false);
}

export function CustomApiResponseListServiceCatalogResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseListServiceCatalogResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ServiceCatalogResponseFromJSON)),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseListServiceCatalogResponseToJSON(json: any): CustomApiResponseListServiceCatalogResponse {
    return CustomApiResponseListServiceCatalogResponseToJSONTyped(json, false);
}

export function CustomApiResponseListServiceCatalogResponseToJSONTyped(value?: CustomApiResponseListServiceCatalogResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ServiceCatalogResponseToJSON)),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

