/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentResponse } from './ContentResponse';
import {
    ContentResponseFromJSON,
    ContentResponseFromJSONTyped,
    ContentResponseToJSON,
    ContentResponseToJSONTyped,
} from './ContentResponse';

/**
 * 
 * @export
 * @interface CustomApiResponseContentResponse
 */
export interface CustomApiResponseContentResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseContentResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseContentResponse
     */
    message?: string;
    /**
     * 
     * @type {ContentResponse}
     * @memberof CustomApiResponseContentResponse
     */
    data?: ContentResponse;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseContentResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseContentResponse
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseContentResponse interface.
 */
export function instanceOfCustomApiResponseContentResponse(value: object): value is CustomApiResponseContentResponse {
    return true;
}

export function CustomApiResponseContentResponseFromJSON(json: any): CustomApiResponseContentResponse {
    return CustomApiResponseContentResponseFromJSONTyped(json, false);
}

export function CustomApiResponseContentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseContentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ContentResponseFromJSON(json['data']),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseContentResponseToJSON(json: any): CustomApiResponseContentResponse {
    return CustomApiResponseContentResponseToJSONTyped(json, false);
}

export function CustomApiResponseContentResponseToJSONTyped(value?: CustomApiResponseContentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': ContentResponseToJSON(value['data']),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

