/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LabTestResponse } from './LabTestResponse';
import {
    LabTestResponseFromJSON,
    LabTestResponseFromJSONTyped,
    LabTestResponseToJSON,
    LabTestResponseToJSONTyped,
} from './LabTestResponse';

/**
 * 
 * @export
 * @interface CustomApiResponseLabTestResponse
 */
export interface CustomApiResponseLabTestResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseLabTestResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseLabTestResponse
     */
    message?: string;
    /**
     * 
     * @type {LabTestResponse}
     * @memberof CustomApiResponseLabTestResponse
     */
    data?: LabTestResponse;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseLabTestResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseLabTestResponse
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseLabTestResponse interface.
 */
export function instanceOfCustomApiResponseLabTestResponse(value: object): value is CustomApiResponseLabTestResponse {
    return true;
}

export function CustomApiResponseLabTestResponseFromJSON(json: any): CustomApiResponseLabTestResponse {
    return CustomApiResponseLabTestResponseFromJSONTyped(json, false);
}

export function CustomApiResponseLabTestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseLabTestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : LabTestResponseFromJSON(json['data']),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseLabTestResponseToJSON(json: any): CustomApiResponseLabTestResponse {
    return CustomApiResponseLabTestResponseToJSONTyped(json, false);
}

export function CustomApiResponseLabTestResponseToJSONTyped(value?: CustomApiResponseLabTestResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': LabTestResponseToJSON(value['data']),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

