/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LabOrderResponse } from './LabOrderResponse';
import {
    LabOrderResponseFromJSON,
    LabOrderResponseFromJSONTyped,
    LabOrderResponseToJSON,
    LabOrderResponseToJSONTyped,
} from './LabOrderResponse';

/**
 * 
 * @export
 * @interface CustomApiResponseLabOrderResponse
 */
export interface CustomApiResponseLabOrderResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseLabOrderResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseLabOrderResponse
     */
    message?: string;
    /**
     * 
     * @type {LabOrderResponse}
     * @memberof CustomApiResponseLabOrderResponse
     */
    data?: LabOrderResponse;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseLabOrderResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseLabOrderResponse
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseLabOrderResponse interface.
 */
export function instanceOfCustomApiResponseLabOrderResponse(value: object): value is CustomApiResponseLabOrderResponse {
    return true;
}

export function CustomApiResponseLabOrderResponseFromJSON(json: any): CustomApiResponseLabOrderResponse {
    return CustomApiResponseLabOrderResponseFromJSONTyped(json, false);
}

export function CustomApiResponseLabOrderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseLabOrderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : LabOrderResponseFromJSON(json['data']),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseLabOrderResponseToJSON(json: any): CustomApiResponseLabOrderResponse {
    return CustomApiResponseLabOrderResponseToJSONTyped(json, false);
}

export function CustomApiResponseLabOrderResponseToJSONTyped(value?: CustomApiResponseLabOrderResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': LabOrderResponseToJSON(value['data']),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

