/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StaffScheduleResponse } from './StaffScheduleResponse';
import {
    StaffScheduleResponseFromJSON,
    StaffScheduleResponseFromJSONTyped,
    StaffScheduleResponseToJSON,
    StaffScheduleResponseToJSONTyped,
} from './StaffScheduleResponse';

/**
 * 
 * @export
 * @interface CustomApiResponseStaffScheduleResponse
 */
export interface CustomApiResponseStaffScheduleResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseStaffScheduleResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseStaffScheduleResponse
     */
    message?: string;
    /**
     * 
     * @type {StaffScheduleResponse}
     * @memberof CustomApiResponseStaffScheduleResponse
     */
    data?: StaffScheduleResponse;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseStaffScheduleResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseStaffScheduleResponse
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseStaffScheduleResponse interface.
 */
export function instanceOfCustomApiResponseStaffScheduleResponse(value: object): value is CustomApiResponseStaffScheduleResponse {
    return true;
}

export function CustomApiResponseStaffScheduleResponseFromJSON(json: any): CustomApiResponseStaffScheduleResponse {
    return CustomApiResponseStaffScheduleResponseFromJSONTyped(json, false);
}

export function CustomApiResponseStaffScheduleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseStaffScheduleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : StaffScheduleResponseFromJSON(json['data']),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseStaffScheduleResponseToJSON(json: any): CustomApiResponseStaffScheduleResponse {
    return CustomApiResponseStaffScheduleResponseToJSONTyped(json, false);
}

export function CustomApiResponseStaffScheduleResponseToJSONTyped(value?: CustomApiResponseStaffScheduleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': StaffScheduleResponseToJSON(value['data']),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

