/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomApiResponseListString
 */
export interface CustomApiResponseListString {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseListString
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseListString
     */
    message?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CustomApiResponseListString
     */
    data?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseListString
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseListString
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseListString interface.
 */
export function instanceOfCustomApiResponseListString(value: object): value is CustomApiResponseListString {
    return true;
}

export function CustomApiResponseListStringFromJSON(json: any): CustomApiResponseListString {
    return CustomApiResponseListStringFromJSONTyped(json, false);
}

export function CustomApiResponseListStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseListString {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : json['data'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseListStringToJSON(json: any): CustomApiResponseListString {
    return CustomApiResponseListStringToJSONTyped(json, false);
}

export function CustomApiResponseListStringToJSONTyped(value?: CustomApiResponseListString | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': value['data'],
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

