/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserProfileResponse } from './UserProfileResponse';
import {
    UserProfileResponseFromJSON,
    UserProfileResponseFromJSONTyped,
    UserProfileResponseToJSON,
    UserProfileResponseToJSONTyped,
} from './UserProfileResponse';

/**
 * 
 * @export
 * @interface CustomApiResponseUserProfileResponse
 */
export interface CustomApiResponseUserProfileResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseUserProfileResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseUserProfileResponse
     */
    message?: string;
    /**
     * 
     * @type {UserProfileResponse}
     * @memberof CustomApiResponseUserProfileResponse
     */
    data?: UserProfileResponse;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseUserProfileResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseUserProfileResponse
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseUserProfileResponse interface.
 */
export function instanceOfCustomApiResponseUserProfileResponse(value: object): value is CustomApiResponseUserProfileResponse {
    return true;
}

export function CustomApiResponseUserProfileResponseFromJSON(json: any): CustomApiResponseUserProfileResponse {
    return CustomApiResponseUserProfileResponseFromJSONTyped(json, false);
}

export function CustomApiResponseUserProfileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseUserProfileResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : UserProfileResponseFromJSON(json['data']),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseUserProfileResponseToJSON(json: any): CustomApiResponseUserProfileResponse {
    return CustomApiResponseUserProfileResponseToJSONTyped(json, false);
}

export function CustomApiResponseUserProfileResponseToJSONTyped(value?: CustomApiResponseUserProfileResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': UserProfileResponseToJSON(value['data']),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

