/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RevenueDailyResponse } from './RevenueDailyResponse';
import {
    RevenueDailyResponseFromJSON,
    RevenueDailyResponseFromJSONTyped,
    RevenueDailyResponseToJSON,
    RevenueDailyResponseToJSONTyped,
} from './RevenueDailyResponse';

/**
 * 
 * @export
 * @interface CustomApiResponseListRevenueDailyResponse
 */
export interface CustomApiResponseListRevenueDailyResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseListRevenueDailyResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseListRevenueDailyResponse
     */
    message?: string;
    /**
     * 
     * @type {Array<RevenueDailyResponse>}
     * @memberof CustomApiResponseListRevenueDailyResponse
     */
    data?: Array<RevenueDailyResponse>;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseListRevenueDailyResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseListRevenueDailyResponse
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseListRevenueDailyResponse interface.
 */
export function instanceOfCustomApiResponseListRevenueDailyResponse(value: object): value is CustomApiResponseListRevenueDailyResponse {
    return true;
}

export function CustomApiResponseListRevenueDailyResponseFromJSON(json: any): CustomApiResponseListRevenueDailyResponse {
    return CustomApiResponseListRevenueDailyResponseFromJSONTyped(json, false);
}

export function CustomApiResponseListRevenueDailyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseListRevenueDailyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(RevenueDailyResponseFromJSON)),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseListRevenueDailyResponseToJSON(json: any): CustomApiResponseListRevenueDailyResponse {
    return CustomApiResponseListRevenueDailyResponseToJSONTyped(json, false);
}

export function CustomApiResponseListRevenueDailyResponseToJSONTyped(value?: CustomApiResponseListRevenueDailyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(RevenueDailyResponseToJSON)),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

