/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VitalSignResponse } from './VitalSignResponse';
import {
    VitalSignResponseFromJSON,
    VitalSignResponseFromJSONTyped,
    VitalSignResponseToJSON,
    VitalSignResponseToJSONTyped,
} from './VitalSignResponse';

/**
 * 
 * @export
 * @interface CustomApiResponseVitalSignResponse
 */
export interface CustomApiResponseVitalSignResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseVitalSignResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseVitalSignResponse
     */
    message?: string;
    /**
     * 
     * @type {VitalSignResponse}
     * @memberof CustomApiResponseVitalSignResponse
     */
    data?: VitalSignResponse;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseVitalSignResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseVitalSignResponse
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseVitalSignResponse interface.
 */
export function instanceOfCustomApiResponseVitalSignResponse(value: object): value is CustomApiResponseVitalSignResponse {
    return true;
}

export function CustomApiResponseVitalSignResponseFromJSON(json: any): CustomApiResponseVitalSignResponse {
    return CustomApiResponseVitalSignResponseFromJSONTyped(json, false);
}

export function CustomApiResponseVitalSignResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseVitalSignResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : VitalSignResponseFromJSON(json['data']),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseVitalSignResponseToJSON(json: any): CustomApiResponseVitalSignResponse {
    return CustomApiResponseVitalSignResponseToJSONTyped(json, false);
}

export function CustomApiResponseVitalSignResponseToJSONTyped(value?: CustomApiResponseVitalSignResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': VitalSignResponseToJSON(value['data']),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

