/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StaffScheduleTemplateResponse } from './StaffScheduleTemplateResponse';
import {
    StaffScheduleTemplateResponseFromJSON,
    StaffScheduleTemplateResponseFromJSONTyped,
    StaffScheduleTemplateResponseToJSON,
    StaffScheduleTemplateResponseToJSONTyped,
} from './StaffScheduleTemplateResponse';

/**
 * 
 * @export
 * @interface CustomApiResponseStaffScheduleTemplateResponse
 */
export interface CustomApiResponseStaffScheduleTemplateResponse {
    /**
     * 
     * @type {number}
     * @memberof CustomApiResponseStaffScheduleTemplateResponse
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseStaffScheduleTemplateResponse
     */
    message?: string;
    /**
     * 
     * @type {StaffScheduleTemplateResponse}
     * @memberof CustomApiResponseStaffScheduleTemplateResponse
     */
    data?: StaffScheduleTemplateResponse;
    /**
     * 
     * @type {Date}
     * @memberof CustomApiResponseStaffScheduleTemplateResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {string}
     * @memberof CustomApiResponseStaffScheduleTemplateResponse
     */
    path?: string;
}

/**
 * Check if a given object implements the CustomApiResponseStaffScheduleTemplateResponse interface.
 */
export function instanceOfCustomApiResponseStaffScheduleTemplateResponse(value: object): value is CustomApiResponseStaffScheduleTemplateResponse {
    return true;
}

export function CustomApiResponseStaffScheduleTemplateResponseFromJSON(json: any): CustomApiResponseStaffScheduleTemplateResponse {
    return CustomApiResponseStaffScheduleTemplateResponseFromJSONTyped(json, false);
}

export function CustomApiResponseStaffScheduleTemplateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomApiResponseStaffScheduleTemplateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : StaffScheduleTemplateResponseFromJSON(json['data']),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'path': json['path'] == null ? undefined : json['path'],
    };
}

export function CustomApiResponseStaffScheduleTemplateResponseToJSON(json: any): CustomApiResponseStaffScheduleTemplateResponse {
    return CustomApiResponseStaffScheduleTemplateResponseToJSONTyped(json, false);
}

export function CustomApiResponseStaffScheduleTemplateResponseToJSONTyped(value?: CustomApiResponseStaffScheduleTemplateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'message': value['message'],
        'data': StaffScheduleTemplateResponseToJSON(value['data']),
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'path': value['path'],
    };
}

