/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoomResponse } from './RoomResponse';
import {
    RoomResponseFromJSON,
    RoomResponseFromJSONTyped,
    RoomResponseToJSON,
    RoomResponseToJSONTyped,
} from './RoomResponse';
import type { ClinicSimpleResponse } from './ClinicSimpleResponse';
import {
    ClinicSimpleResponseFromJSON,
    ClinicSimpleResponseFromJSONTyped,
    ClinicSimpleResponseToJSON,
    ClinicSimpleResponseToJSONTyped,
} from './ClinicSimpleResponse';

/**
 * 
 * @export
 * @interface DepartmentResponse
 */
export interface DepartmentResponse {
    /**
     * 
     * @type {string}
     * @memberof DepartmentResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DepartmentResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DepartmentResponse
     */
    description?: string;
    /**
     * 
     * @type {ClinicSimpleResponse}
     * @memberof DepartmentResponse
     */
    clinic?: ClinicSimpleResponse;
    /**
     * 
     * @type {Array<RoomResponse>}
     * @memberof DepartmentResponse
     */
    rooms?: Array<RoomResponse>;
}

/**
 * Check if a given object implements the DepartmentResponse interface.
 */
export function instanceOfDepartmentResponse(value: object): value is DepartmentResponse {
    return true;
}

export function DepartmentResponseFromJSON(json: any): DepartmentResponse {
    return DepartmentResponseFromJSONTyped(json, false);
}

export function DepartmentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepartmentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'clinic': json['clinic'] == null ? undefined : ClinicSimpleResponseFromJSON(json['clinic']),
        'rooms': json['rooms'] == null ? undefined : ((json['rooms'] as Array<any>).map(RoomResponseFromJSON)),
    };
}

export function DepartmentResponseToJSON(json: any): DepartmentResponse {
    return DepartmentResponseToJSONTyped(json, false);
}

export function DepartmentResponseToJSONTyped(value?: DepartmentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'clinic': ClinicSimpleResponseToJSON(value['clinic']),
        'rooms': value['rooms'] == null ? undefined : ((value['rooms'] as Array<any>).map(RoomResponseToJSON)),
    };
}

