/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DepartmentRequest
 */
export interface DepartmentRequest {
    /**
     * 
     * @type {string}
     * @memberof DepartmentRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DepartmentRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof DepartmentRequest
     */
    clinicId: string;
}

/**
 * Check if a given object implements the DepartmentRequest interface.
 */
export function instanceOfDepartmentRequest(value: object): value is DepartmentRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('clinicId' in value) || value['clinicId'] === undefined) return false;
    return true;
}

export function DepartmentRequestFromJSON(json: any): DepartmentRequest {
    return DepartmentRequestFromJSONTyped(json, false);
}

export function DepartmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DepartmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'clinicId': json['clinicId'],
    };
}

export function DepartmentRequestToJSON(json: any): DepartmentRequest {
    return DepartmentRequestToJSONTyped(json, false);
}

export function DepartmentRequestToJSONTyped(value?: DepartmentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'clinicId': value['clinicId'],
    };
}

