/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceSessionResponse
 */
export interface DeviceSessionResponse {
    /**
     * 
     * @type {string}
     * @memberof DeviceSessionResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceSessionResponse
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceSessionResponse
     */
    deviceName?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceSessionResponse
     */
    ipAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof DeviceSessionResponse
     */
    userAgent?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DeviceSessionResponse
     */
    trusted?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof DeviceSessionResponse
     */
    expiresIn?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof DeviceSessionResponse
     */
    revoked?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DeviceSessionResponse
     */
    rememberMe?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof DeviceSessionResponse
     */
    lastLoginAt?: Date;
}

/**
 * Check if a given object implements the DeviceSessionResponse interface.
 */
export function instanceOfDeviceSessionResponse(value: object): value is DeviceSessionResponse {
    return true;
}

export function DeviceSessionResponseFromJSON(json: any): DeviceSessionResponse {
    return DeviceSessionResponseFromJSONTyped(json, false);
}

export function DeviceSessionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceSessionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'deviceName': json['deviceName'] == null ? undefined : json['deviceName'],
        'ipAddress': json['ipAddress'] == null ? undefined : json['ipAddress'],
        'userAgent': json['userAgent'] == null ? undefined : json['userAgent'],
        'trusted': json['trusted'] == null ? undefined : json['trusted'],
        'expiresIn': json['expiresIn'] == null ? undefined : (new Date(json['expiresIn'])),
        'revoked': json['revoked'] == null ? undefined : json['revoked'],
        'rememberMe': json['rememberMe'] == null ? undefined : json['rememberMe'],
        'lastLoginAt': json['lastLoginAt'] == null ? undefined : (new Date(json['lastLoginAt'])),
    };
}

export function DeviceSessionResponseToJSON(json: any): DeviceSessionResponse {
    return DeviceSessionResponseToJSONTyped(json, false);
}

export function DeviceSessionResponseToJSONTyped(value?: DeviceSessionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdBy': value['createdBy'],
        'deviceName': value['deviceName'],
        'ipAddress': value['ipAddress'],
        'userAgent': value['userAgent'],
        'trusted': value['trusted'],
        'expiresIn': value['expiresIn'] == null ? value['expiresIn'] : value['expiresIn'].toISOString(),
        'revoked': value['revoked'],
        'rememberMe': value['rememberMe'],
        'lastLoginAt': value['lastLoginAt'] == null ? value['lastLoginAt'] : value['lastLoginAt'].toISOString(),
    };
}

