/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DiagnosisRequest
 */
export interface DiagnosisRequest {
    /**
     * 
     * @type {string}
     * @memberof DiagnosisRequest
     */
    examinationId?: string;
    /**
     * 
     * @type {string}
     * @memberof DiagnosisRequest
     */
    icdCode?: string;
    /**
     * 
     * @type {string}
     * @memberof DiagnosisRequest
     */
    diseaseName?: string;
    /**
     * 
     * @type {string}
     * @memberof DiagnosisRequest
     */
    note?: string;
}

/**
 * Check if a given object implements the DiagnosisRequest interface.
 */
export function instanceOfDiagnosisRequest(value: object): value is DiagnosisRequest {
    return true;
}

export function DiagnosisRequestFromJSON(json: any): DiagnosisRequest {
    return DiagnosisRequestFromJSONTyped(json, false);
}

export function DiagnosisRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiagnosisRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'examinationId': json['examinationId'] == null ? undefined : json['examinationId'],
        'icdCode': json['icdCode'] == null ? undefined : json['icdCode'],
        'diseaseName': json['diseaseName'] == null ? undefined : json['diseaseName'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function DiagnosisRequestToJSON(json: any): DiagnosisRequest {
    return DiagnosisRequestToJSONTyped(json, false);
}

export function DiagnosisRequestToJSONTyped(value?: DiagnosisRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'examinationId': value['examinationId'],
        'icdCode': value['icdCode'],
        'diseaseName': value['diseaseName'],
        'note': value['note'],
    };
}

