/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IcdCodeResponse } from './IcdCodeResponse';
import {
    IcdCodeResponseFromJSON,
    IcdCodeResponseFromJSONTyped,
    IcdCodeResponseToJSON,
    IcdCodeResponseToJSONTyped,
} from './IcdCodeResponse';

/**
 * 
 * @export
 * @interface DiagnosisResponse
 */
export interface DiagnosisResponse {
    /**
     * 
     * @type {string}
     * @memberof DiagnosisResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DiagnosisResponse
     */
    note?: string;
    /**
     * 
     * @type {IcdCodeResponse}
     * @memberof DiagnosisResponse
     */
    icdCode?: IcdCodeResponse;
}

/**
 * Check if a given object implements the DiagnosisResponse interface.
 */
export function instanceOfDiagnosisResponse(value: object): value is DiagnosisResponse {
    return true;
}

export function DiagnosisResponseFromJSON(json: any): DiagnosisResponse {
    return DiagnosisResponseFromJSONTyped(json, false);
}

export function DiagnosisResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DiagnosisResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'note': json['note'] == null ? undefined : json['note'],
        'icdCode': json['icdCode'] == null ? undefined : IcdCodeResponseFromJSON(json['icdCode']),
    };
}

export function DiagnosisResponseToJSON(json: any): DiagnosisResponse {
    return DiagnosisResponseToJSONTyped(json, false);
}

export function DiagnosisResponseToJSONTyped(value?: DiagnosisResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'note': value['note'],
        'icdCode': IcdCodeResponseToJSON(value['icdCode']),
    };
}

