/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DispenseRecordRequest
 */
export interface DispenseRecordRequest {
    /**
     * 
     * @type {string}
     * @memberof DispenseRecordRequest
     */
    prescriptionId?: string;
    /**
     * 
     * @type {string}
     * @memberof DispenseRecordRequest
     */
    dispensedById?: string;
    /**
     * 
     * @type {string}
     * @memberof DispenseRecordRequest
     */
    status?: DispenseRecordRequestStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof DispenseRecordRequest
     */
    dispensedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof DispenseRecordRequest
     */
    totalCost?: number;
    /**
     * 
     * @type {string}
     * @memberof DispenseRecordRequest
     */
    note?: string;
}


/**
 * @export
 */
export const DispenseRecordRequestStatusEnum = {
    Pending: 'PENDING',
    Dispensed: 'DISPENSED',
    Cancelled: 'CANCELLED'
} as const;
export type DispenseRecordRequestStatusEnum = typeof DispenseRecordRequestStatusEnum[keyof typeof DispenseRecordRequestStatusEnum];


/**
 * Check if a given object implements the DispenseRecordRequest interface.
 */
export function instanceOfDispenseRecordRequest(value: object): value is DispenseRecordRequest {
    return true;
}

export function DispenseRecordRequestFromJSON(json: any): DispenseRecordRequest {
    return DispenseRecordRequestFromJSONTyped(json, false);
}

export function DispenseRecordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DispenseRecordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'prescriptionId': json['prescriptionId'] == null ? undefined : json['prescriptionId'],
        'dispensedById': json['dispensedById'] == null ? undefined : json['dispensedById'],
        'status': json['status'] == null ? undefined : json['status'],
        'dispensedAt': json['dispensedAt'] == null ? undefined : (new Date(json['dispensedAt'])),
        'totalCost': json['totalCost'] == null ? undefined : json['totalCost'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function DispenseRecordRequestToJSON(json: any): DispenseRecordRequest {
    return DispenseRecordRequestToJSONTyped(json, false);
}

export function DispenseRecordRequestToJSONTyped(value?: DispenseRecordRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prescriptionId': value['prescriptionId'],
        'dispensedById': value['dispensedById'],
        'status': value['status'],
        'dispensedAt': value['dispensedAt'] == null ? value['dispensedAt'] : value['dispensedAt'].toISOString(),
        'totalCost': value['totalCost'],
        'note': value['note'],
    };
}

