/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmergencyContactResponse
 */
export interface EmergencyContactResponse {
    /**
     * 
     * @type {string}
     * @memberof EmergencyContactResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof EmergencyContactResponse
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof EmergencyContactResponse
     */
    relationship?: string;
    /**
     * 
     * @type {string}
     * @memberof EmergencyContactResponse
     */
    phone?: string;
}

/**
 * Check if a given object implements the EmergencyContactResponse interface.
 */
export function instanceOfEmergencyContactResponse(value: object): value is EmergencyContactResponse {
    return true;
}

export function EmergencyContactResponseFromJSON(json: any): EmergencyContactResponse {
    return EmergencyContactResponseFromJSONTyped(json, false);
}

export function EmergencyContactResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmergencyContactResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'relationship': json['relationship'] == null ? undefined : json['relationship'],
        'phone': json['phone'] == null ? undefined : json['phone'],
    };
}

export function EmergencyContactResponseToJSON(json: any): EmergencyContactResponse {
    return EmergencyContactResponseToJSONTyped(json, false);
}

export function EmergencyContactResponseToJSONTyped(value?: EmergencyContactResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'fullName': value['fullName'],
        'relationship': value['relationship'],
        'phone': value['phone'],
    };
}

