/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Filter } from './Filter';
import {
    FilterFromJSON,
    FilterFromJSONTyped,
    FilterToJSON,
    FilterToJSONTyped,
} from './Filter';

/**
 * 
 * @export
 * @interface FilterGroup
 */
export interface FilterGroup {
    /**
     * 
     * @type {string}
     * @memberof FilterGroup
     */
    operator?: FilterGroupOperatorEnum;
    /**
     * 
     * @type {Array<Filter>}
     * @memberof FilterGroup
     */
    filters?: Array<Filter>;
    /**
     * 
     * @type {Array<FilterGroup>}
     * @memberof FilterGroup
     */
    subGroups?: Array<FilterGroup>;
    /**
     * 
     * @type {boolean}
     * @memberof FilterGroup
     */
    empty?: boolean;
}


/**
 * @export
 */
export const FilterGroupOperatorEnum = {
    And: 'AND',
    Or: 'OR',
    Not: 'NOT'
} as const;
export type FilterGroupOperatorEnum = typeof FilterGroupOperatorEnum[keyof typeof FilterGroupOperatorEnum];


/**
 * Check if a given object implements the FilterGroup interface.
 */
export function instanceOfFilterGroup(value: object): value is FilterGroup {
    return true;
}

export function FilterGroupFromJSON(json: any): FilterGroup {
    return FilterGroupFromJSONTyped(json, false);
}

export function FilterGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): FilterGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'operator': json['operator'] == null ? undefined : json['operator'],
        'filters': json['filters'] == null ? undefined : ((json['filters'] as Array<any>).map(FilterFromJSON)),
        'subGroups': json['subGroups'] == null ? undefined : ((json['subGroups'] as Array<any>).map(FilterGroupFromJSON)),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function FilterGroupToJSON(json: any): FilterGroup {
    return FilterGroupToJSONTyped(json, false);
}

export function FilterGroupToJSONTyped(value?: FilterGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'operator': value['operator'],
        'filters': value['filters'] == null ? undefined : ((value['filters'] as Array<any>).map(FilterToJSON)),
        'subGroups': value['subGroups'] == null ? undefined : ((value['subGroups'] as Array<any>).map(FilterGroupToJSON)),
        'empty': value['empty'],
    };
}

