/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CustomApiResponseObject } from './CustomApiResponseObject';
import {
    instanceOfCustomApiResponseObject,
    CustomApiResponseObjectFromJSON,
    CustomApiResponseObjectFromJSONTyped,
    CustomApiResponseObjectToJSON,
} from './CustomApiResponseObject';
import type { CustomApiResponseVoid } from './CustomApiResponseVoid';
import {
    instanceOfCustomApiResponseVoid,
    CustomApiResponseVoidFromJSON,
    CustomApiResponseVoidFromJSONTyped,
    CustomApiResponseVoidToJSON,
} from './CustomApiResponseVoid';

/**
 * @type GetPatientById400Response
 * 
 * @export
 */
export type GetPatientById400Response = CustomApiResponseObject | CustomApiResponseVoid;

export function GetPatientById400ResponseFromJSON(json: any): GetPatientById400Response {
    return GetPatientById400ResponseFromJSONTyped(json, false);
}

export function GetPatientById400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPatientById400Response {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfCustomApiResponseObject(json)) {
        return CustomApiResponseObjectFromJSONTyped(json, true);
    }
    if (instanceOfCustomApiResponseVoid(json)) {
        return CustomApiResponseVoidFromJSONTyped(json, true);
    }
    return {} as any;
}

export function GetPatientById400ResponseToJSON(json: any): any {
    return GetPatientById400ResponseToJSONTyped(json, false);
}

export function GetPatientById400ResponseToJSONTyped(value?: GetPatientById400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfCustomApiResponseObject(value)) {
        return CustomApiResponseObjectToJSON(value as CustomApiResponseObject);
    }
    if (instanceOfCustomApiResponseVoid(value)) {
        return CustomApiResponseVoidToJSON(value as CustomApiResponseVoid);
    }
    return {};
}

