/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IcdCodeRequest
 */
export interface IcdCodeRequest {
    /**
     * 
     * @type {string}
     * @memberof IcdCodeRequest
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof IcdCodeRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof IcdCodeRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof IcdCodeRequest
     */
    chapter?: string;
    /**
     * 
     * @type {string}
     * @memberof IcdCodeRequest
     */
    icdVersion?: string;
}

/**
 * Check if a given object implements the IcdCodeRequest interface.
 */
export function instanceOfIcdCodeRequest(value: object): value is IcdCodeRequest {
    return true;
}

export function IcdCodeRequestFromJSON(json: any): IcdCodeRequest {
    return IcdCodeRequestFromJSONTyped(json, false);
}

export function IcdCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IcdCodeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'chapter': json['chapter'] == null ? undefined : json['chapter'],
        'icdVersion': json['icdVersion'] == null ? undefined : json['icdVersion'],
    };
}

export function IcdCodeRequestToJSON(json: any): IcdCodeRequest {
    return IcdCodeRequestToJSONTyped(json, false);
}

export function IcdCodeRequestToJSONTyped(value?: IcdCodeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'name': value['name'],
        'description': value['description'],
        'chapter': value['chapter'],
        'icdVersion': value['icdVersion'],
    };
}

