/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoomResponse } from './RoomResponse';
import {
    RoomResponseFromJSON,
    RoomResponseFromJSONTyped,
    RoomResponseToJSON,
    RoomResponseToJSONTyped,
} from './RoomResponse';
import type { PatientResponse } from './PatientResponse';
import {
    PatientResponseFromJSON,
    PatientResponseFromJSONTyped,
    PatientResponseToJSON,
    PatientResponseToJSONTyped,
} from './PatientResponse';
import type { ExaminationResponse } from './ExaminationResponse';
import {
    ExaminationResponseFromJSON,
    ExaminationResponseFromJSONTyped,
    ExaminationResponseToJSON,
    ExaminationResponseToJSONTyped,
} from './ExaminationResponse';
import type { StaffResponse } from './StaffResponse';
import {
    StaffResponseFromJSON,
    StaffResponseFromJSONTyped,
    StaffResponseToJSON,
    StaffResponseToJSONTyped,
} from './StaffResponse';
import type { InvoiceItemResponse } from './InvoiceItemResponse';
import {
    InvoiceItemResponseFromJSON,
    InvoiceItemResponseFromJSONTyped,
    InvoiceItemResponseToJSON,
    InvoiceItemResponseToJSONTyped,
} from './InvoiceItemResponse';

/**
 * 
 * @export
 * @interface InvoiceResponse
 */
export interface InvoiceResponse {
    /**
     * 
     * @type {string}
     * @memberof InvoiceResponse
     */
    id?: string;
    /**
     * 
     * @type {PatientResponse}
     * @memberof InvoiceResponse
     */
    patient?: PatientResponse;
    /**
     * 
     * @type {ExaminationResponse}
     * @memberof InvoiceResponse
     */
    examination?: ExaminationResponse;
    /**
     * 
     * @type {string}
     * @memberof InvoiceResponse
     */
    invoiceNumber?: string;
    /**
     * 
     * @type {Date}
     * @memberof InvoiceResponse
     */
    issueDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof InvoiceResponse
     */
    totalAmount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof InvoiceResponse
     */
    paid?: boolean;
    /**
     * 
     * @type {string}
     * @memberof InvoiceResponse
     */
    note?: string;
    /**
     * 
     * @type {Set<InvoiceItemResponse>}
     * @memberof InvoiceResponse
     */
    items?: Set<InvoiceItemResponse>;
    /**
     * 
     * @type {RoomResponse}
     * @memberof InvoiceResponse
     */
    room?: RoomResponse;
    /**
     * 
     * @type {StaffResponse}
     * @memberof InvoiceResponse
     */
    assignedStaff?: StaffResponse;
}

/**
 * Check if a given object implements the InvoiceResponse interface.
 */
export function instanceOfInvoiceResponse(value: object): value is InvoiceResponse {
    return true;
}

export function InvoiceResponseFromJSON(json: any): InvoiceResponse {
    return InvoiceResponseFromJSONTyped(json, false);
}

export function InvoiceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'patient': json['patient'] == null ? undefined : PatientResponseFromJSON(json['patient']),
        'examination': json['examination'] == null ? undefined : ExaminationResponseFromJSON(json['examination']),
        'invoiceNumber': json['invoiceNumber'] == null ? undefined : json['invoiceNumber'],
        'issueDate': json['issueDate'] == null ? undefined : (new Date(json['issueDate'])),
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
        'paid': json['paid'] == null ? undefined : json['paid'],
        'note': json['note'] == null ? undefined : json['note'],
        'items': json['items'] == null ? undefined : (new Set((json['items'] as Array<any>).map(InvoiceItemResponseFromJSON))),
        'room': json['room'] == null ? undefined : RoomResponseFromJSON(json['room']),
        'assignedStaff': json['assignedStaff'] == null ? undefined : StaffResponseFromJSON(json['assignedStaff']),
    };
}

export function InvoiceResponseToJSON(json: any): InvoiceResponse {
    return InvoiceResponseToJSONTyped(json, false);
}

export function InvoiceResponseToJSONTyped(value?: InvoiceResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'patient': PatientResponseToJSON(value['patient']),
        'examination': ExaminationResponseToJSON(value['examination']),
        'invoiceNumber': value['invoiceNumber'],
        'issueDate': value['issueDate'] == null ? value['issueDate'] : value['issueDate'].toISOString(),
        'totalAmount': value['totalAmount'],
        'paid': value['paid'],
        'note': value['note'],
        'items': value['items'] == null ? undefined : (Array.from(value['items'] as Set<any>).map(InvoiceItemResponseToJSON)),
        'room': RoomResponseToJSON(value['room']),
        'assignedStaff': StaffResponseToJSON(value['assignedStaff']),
    };
}

