/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LabOrderRequest
 */
export interface LabOrderRequest {
    /**
     * 
     * @type {string}
     * @memberof LabOrderRequest
     */
    patientId?: string;
    /**
     * 
     * @type {string}
     * @memberof LabOrderRequest
     */
    requestedById?: string;
    /**
     * 
     * @type {string}
     * @memberof LabOrderRequest
     */
    examinationId?: string;
    /**
     * 
     * @type {string}
     * @memberof LabOrderRequest
     */
    status?: LabOrderRequestStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof LabOrderRequest
     */
    orderCode?: string;
}


/**
 * @export
 */
export const LabOrderRequestStatusEnum = {
    Pending: 'PENDING',
    InProgress: 'IN_PROGRESS',
    Completed: 'COMPLETED',
    Verified: 'VERIFIED',
    Cancelled: 'CANCELLED'
} as const;
export type LabOrderRequestStatusEnum = typeof LabOrderRequestStatusEnum[keyof typeof LabOrderRequestStatusEnum];


/**
 * Check if a given object implements the LabOrderRequest interface.
 */
export function instanceOfLabOrderRequest(value: object): value is LabOrderRequest {
    return true;
}

export function LabOrderRequestFromJSON(json: any): LabOrderRequest {
    return LabOrderRequestFromJSONTyped(json, false);
}

export function LabOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'patientId': json['patientId'] == null ? undefined : json['patientId'],
        'requestedById': json['requestedById'] == null ? undefined : json['requestedById'],
        'examinationId': json['examinationId'] == null ? undefined : json['examinationId'],
        'status': json['status'] == null ? undefined : json['status'],
        'orderCode': json['orderCode'] == null ? undefined : json['orderCode'],
    };
}

export function LabOrderRequestToJSON(json: any): LabOrderRequest {
    return LabOrderRequestToJSONTyped(json, false);
}

export function LabOrderRequestToJSONTyped(value?: LabOrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'patientId': value['patientId'],
        'requestedById': value['requestedById'],
        'examinationId': value['examinationId'],
        'status': value['status'],
        'orderCode': value['orderCode'],
    };
}

