/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LabTestResponse
 */
export interface LabTestResponse {
    /**
     * 
     * @type {string}
     * @memberof LabTestResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof LabTestResponse
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof LabTestResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof LabTestResponse
     */
    category?: string;
    /**
     * 
     * @type {number}
     * @memberof LabTestResponse
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof LabTestResponse
     */
    unit?: string;
    /**
     * 
     * @type {string}
     * @memberof LabTestResponse
     */
    referenceRange?: string;
    /**
     * 
     * @type {string}
     * @memberof LabTestResponse
     */
    description?: string;
}

/**
 * Check if a given object implements the LabTestResponse interface.
 */
export function instanceOfLabTestResponse(value: object): value is LabTestResponse {
    return true;
}

export function LabTestResponseFromJSON(json: any): LabTestResponse {
    return LabTestResponseFromJSONTyped(json, false);
}

export function LabTestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabTestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'code': json['code'] == null ? undefined : json['code'],
        'name': json['name'] == null ? undefined : json['name'],
        'category': json['category'] == null ? undefined : json['category'],
        'price': json['price'] == null ? undefined : json['price'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        'referenceRange': json['referenceRange'] == null ? undefined : json['referenceRange'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function LabTestResponseToJSON(json: any): LabTestResponse {
    return LabTestResponseToJSONTyped(json, false);
}

export function LabTestResponseToJSONTyped(value?: LabTestResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'code': value['code'],
        'name': value['name'],
        'category': value['category'],
        'price': value['price'],
        'unit': value['unit'],
        'referenceRange': value['referenceRange'],
        'description': value['description'],
    };
}

