/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LargeBlobAuthenticationInput
 */
export interface LargeBlobAuthenticationInput {
    /**
     * 
     * @type {boolean}
     * @memberof LargeBlobAuthenticationInput
     */
    read?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LargeBlobAuthenticationInput
     */
    write?: string;
}

/**
 * Check if a given object implements the LargeBlobAuthenticationInput interface.
 */
export function instanceOfLargeBlobAuthenticationInput(value: object): value is LargeBlobAuthenticationInput {
    return true;
}

export function LargeBlobAuthenticationInputFromJSON(json: any): LargeBlobAuthenticationInput {
    return LargeBlobAuthenticationInputFromJSONTyped(json, false);
}

export function LargeBlobAuthenticationInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): LargeBlobAuthenticationInput {
    if (json == null) {
        return json;
    }
    return {
        
        'read': json['read'] == null ? undefined : json['read'],
        'write': json['write'] == null ? undefined : json['write'],
    };
}

export function LargeBlobAuthenticationInputToJSON(json: any): LargeBlobAuthenticationInput {
    return LargeBlobAuthenticationInputToJSONTyped(json, false);
}

export function LargeBlobAuthenticationInputToJSONTyped(value?: LargeBlobAuthenticationInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'read': value['read'],
        'write': value['write'],
    };
}

