/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MedicineRequest
 */
export interface MedicineRequest {
    /**
     * 
     * @type {string}
     * @memberof MedicineRequest
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof MedicineRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof MedicineRequest
     */
    activeIngredient?: string;
    /**
     * 
     * @type {string}
     * @memberof MedicineRequest
     */
    dosageForm?: string;
    /**
     * 
     * @type {string}
     * @memberof MedicineRequest
     */
    strength?: string;
    /**
     * 
     * @type {number}
     * @memberof MedicineRequest
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof MedicineRequest
     */
    unit?: string;
    /**
     * 
     * @type {string}
     * @memberof MedicineRequest
     */
    description?: string;
}

/**
 * Check if a given object implements the MedicineRequest interface.
 */
export function instanceOfMedicineRequest(value: object): value is MedicineRequest {
    return true;
}

export function MedicineRequestFromJSON(json: any): MedicineRequest {
    return MedicineRequestFromJSONTyped(json, false);
}

export function MedicineRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MedicineRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'name': json['name'] == null ? undefined : json['name'],
        'activeIngredient': json['activeIngredient'] == null ? undefined : json['activeIngredient'],
        'dosageForm': json['dosageForm'] == null ? undefined : json['dosageForm'],
        'strength': json['strength'] == null ? undefined : json['strength'],
        'price': json['price'] == null ? undefined : json['price'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function MedicineRequestToJSON(json: any): MedicineRequest {
    return MedicineRequestToJSONTyped(json, false);
}

export function MedicineRequestToJSONTyped(value?: MedicineRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'name': value['name'],
        'activeIngredient': value['activeIngredient'],
        'dosageForm': value['dosageForm'],
        'strength': value['strength'],
        'price': value['price'],
        'unit': value['unit'],
        'description': value['description'],
    };
}

