/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoomResponse } from './RoomResponse';
import {
    RoomResponseFromJSON,
    RoomResponseFromJSONTyped,
    RoomResponseToJSON,
    RoomResponseToJSONTyped,
} from './RoomResponse';
import type { PatientResponse } from './PatientResponse';
import {
    PatientResponseFromJSON,
    PatientResponseFromJSONTyped,
    PatientResponseToJSON,
    PatientResponseToJSONTyped,
} from './PatientResponse';
import type { DeviceInfo } from './DeviceInfo';
import {
    DeviceInfoFromJSON,
    DeviceInfoFromJSONTyped,
    DeviceInfoToJSON,
    DeviceInfoToJSONTyped,
} from './DeviceInfo';
import type { StaffResponse } from './StaffResponse';
import {
    StaffResponseFromJSON,
    StaffResponseFromJSONTyped,
    StaffResponseToJSON,
    StaffResponseToJSONTyped,
} from './StaffResponse';
import type { SimpleProfileResponse } from './SimpleProfileResponse';
import {
    SimpleProfileResponseFromJSON,
    SimpleProfileResponseFromJSONTyped,
    SimpleProfileResponseToJSON,
    SimpleProfileResponseToJSONTyped,
} from './SimpleProfileResponse';
import type { RoleNameResponse } from './RoleNameResponse';
import {
    RoleNameResponseFromJSON,
    RoleNameResponseFromJSONTyped,
    RoleNameResponseToJSON,
    RoleNameResponseToJSONTyped,
} from './RoleNameResponse';

/**
 * 
 * @export
 * @interface MeResponse
 */
export interface MeResponse {
    /**
     * 
     * @type {string}
     * @memberof MeResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof MeResponse
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof MeResponse
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof MeResponse
     */
    phone?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MeResponse
     */
    active?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MeResponse
     */
    locked?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MeResponse
     */
    mfaEnabled?: boolean;
    /**
     * 
     * @type {SimpleProfileResponse}
     * @memberof MeResponse
     */
    userProfile?: SimpleProfileResponse;
    /**
     * 
     * @type {boolean}
     * @memberof MeResponse
     */
    firstLogin?: boolean;
    /**
     * 
     * @type {Set<RoleNameResponse>}
     * @memberof MeResponse
     */
    roles?: Set<RoleNameResponse>;
    /**
     * 
     * @type {DeviceInfo}
     * @memberof MeResponse
     */
    device?: DeviceInfo;
    /**
     * 
     * @type {StaffResponse}
     * @memberof MeResponse
     */
    staff?: StaffResponse;
    /**
     * 
     * @type {PatientResponse}
     * @memberof MeResponse
     */
    patient?: PatientResponse;
    /**
     * 
     * @type {RoomResponse}
     * @memberof MeResponse
     */
    room?: RoomResponse;
}

/**
 * Check if a given object implements the MeResponse interface.
 */
export function instanceOfMeResponse(value: object): value is MeResponse {
    return true;
}

export function MeResponseFromJSON(json: any): MeResponse {
    return MeResponseFromJSONTyped(json, false);
}

export function MeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'username': json['username'] == null ? undefined : json['username'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'active': json['active'] == null ? undefined : json['active'],
        'locked': json['locked'] == null ? undefined : json['locked'],
        'mfaEnabled': json['mfaEnabled'] == null ? undefined : json['mfaEnabled'],
        'userProfile': json['userProfile'] == null ? undefined : SimpleProfileResponseFromJSON(json['userProfile']),
        'firstLogin': json['firstLogin'] == null ? undefined : json['firstLogin'],
        'roles': json['roles'] == null ? undefined : (new Set((json['roles'] as Array<any>).map(RoleNameResponseFromJSON))),
        'device': json['device'] == null ? undefined : DeviceInfoFromJSON(json['device']),
        'staff': json['staff'] == null ? undefined : StaffResponseFromJSON(json['staff']),
        'patient': json['patient'] == null ? undefined : PatientResponseFromJSON(json['patient']),
        'room': json['room'] == null ? undefined : RoomResponseFromJSON(json['room']),
    };
}

export function MeResponseToJSON(json: any): MeResponse {
    return MeResponseToJSONTyped(json, false);
}

export function MeResponseToJSONTyped(value?: MeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'email': value['email'],
        'phone': value['phone'],
        'active': value['active'],
        'locked': value['locked'],
        'mfaEnabled': value['mfaEnabled'],
        'userProfile': SimpleProfileResponseToJSON(value['userProfile']),
        'firstLogin': value['firstLogin'],
        'roles': value['roles'] == null ? undefined : (Array.from(value['roles'] as Set<any>).map(RoleNameResponseToJSON)),
        'device': DeviceInfoToJSON(value['device']),
        'staff': StaffResponseToJSON(value['staff']),
        'patient': PatientResponseToJSON(value['patient']),
        'room': RoomResponseToJSON(value['room']),
    };
}

