/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MfaConfigResponse
 */
export interface MfaConfigResponse {
    /**
     * 
     * @type {string}
     * @memberof MfaConfigResponse
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof MfaConfigResponse
     */
    createdDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof MfaConfigResponse
     */
    mfaType?: MfaConfigResponseMfaTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof MfaConfigResponse
     */
    contact?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MfaConfigResponse
     */
    primary?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof MfaConfigResponse
     */
    lastVerifiedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof MfaConfigResponse
     */
    deviceName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MfaConfigResponse
     */
    revoked?: boolean;
}


/**
 * @export
 */
export const MfaConfigResponseMfaTypeEnum = {
    Totp: 'TOTP',
    Sms: 'SMS',
    Email: 'EMAIL',
    PushNotification: 'PUSH_NOTIFICATION',
    Passkey: 'PASSKEY',
    EmailVerification: 'EMAIL_VERIFICATION'
} as const;
export type MfaConfigResponseMfaTypeEnum = typeof MfaConfigResponseMfaTypeEnum[keyof typeof MfaConfigResponseMfaTypeEnum];


/**
 * Check if a given object implements the MfaConfigResponse interface.
 */
export function instanceOfMfaConfigResponse(value: object): value is MfaConfigResponse {
    return true;
}

export function MfaConfigResponseFromJSON(json: any): MfaConfigResponse {
    return MfaConfigResponseFromJSONTyped(json, false);
}

export function MfaConfigResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MfaConfigResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdDate': json['createdDate'] == null ? undefined : (new Date(json['createdDate'])),
        'mfaType': json['mfaType'] == null ? undefined : json['mfaType'],
        'contact': json['contact'] == null ? undefined : json['contact'],
        'primary': json['primary'] == null ? undefined : json['primary'],
        'lastVerifiedAt': json['lastVerifiedAt'] == null ? undefined : (new Date(json['lastVerifiedAt'])),
        'deviceName': json['deviceName'] == null ? undefined : json['deviceName'],
        'revoked': json['revoked'] == null ? undefined : json['revoked'],
    };
}

export function MfaConfigResponseToJSON(json: any): MfaConfigResponse {
    return MfaConfigResponseToJSONTyped(json, false);
}

export function MfaConfigResponseToJSONTyped(value?: MfaConfigResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdDate': value['createdDate'] == null ? value['createdDate'] : value['createdDate'].toISOString(),
        'mfaType': value['mfaType'],
        'contact': value['contact'],
        'primary': value['primary'],
        'lastVerifiedAt': value['lastVerifiedAt'] == null ? value['lastVerifiedAt'] : value['lastVerifiedAt'].toISOString(),
        'deviceName': value['deviceName'],
        'revoked': value['revoked'],
    };
}

