/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MfaDisableRequest
 */
export interface MfaDisableRequest {
    /**
     * 
     * @type {string}
     * @memberof MfaDisableRequest
     */
    verificationMethod: string;
    /**
     * 
     * @type {string}
     * @memberof MfaDisableRequest
     */
    code: string;
}

/**
 * Check if a given object implements the MfaDisableRequest interface.
 */
export function instanceOfMfaDisableRequest(value: object): value is MfaDisableRequest {
    if (!('verificationMethod' in value) || value['verificationMethod'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function MfaDisableRequestFromJSON(json: any): MfaDisableRequest {
    return MfaDisableRequestFromJSONTyped(json, false);
}

export function MfaDisableRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MfaDisableRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'verificationMethod': json['verificationMethod'],
        'code': json['code'],
    };
}

export function MfaDisableRequestToJSON(json: any): MfaDisableRequest {
    return MfaDisableRequestToJSONTyped(json, false);
}

export function MfaDisableRequestToJSONTyped(value?: MfaDisableRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verificationMethod': value['verificationMethod'],
        'code': value['code'],
    };
}

