/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MfaVerifyRequest
 */
export interface MfaVerifyRequest {
    /**
     * 
     * @type {string}
     * @memberof MfaVerifyRequest
     */
    challengeId?: string;
    /**
     * 
     * @type {string}
     * @memberof MfaVerifyRequest
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof MfaVerifyRequest
     */
    deviceId: string;
    /**
     * 
     * @type {boolean}
     * @memberof MfaVerifyRequest
     */
    rememberMe?: boolean;
}

/**
 * Check if a given object implements the MfaVerifyRequest interface.
 */
export function instanceOfMfaVerifyRequest(value: object): value is MfaVerifyRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('deviceId' in value) || value['deviceId'] === undefined) return false;
    return true;
}

export function MfaVerifyRequestFromJSON(json: any): MfaVerifyRequest {
    return MfaVerifyRequestFromJSONTyped(json, false);
}

export function MfaVerifyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MfaVerifyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'challengeId': json['challengeId'] == null ? undefined : json['challengeId'],
        'code': json['code'],
        'deviceId': json['deviceId'],
        'rememberMe': json['rememberMe'] == null ? undefined : json['rememberMe'],
    };
}

export function MfaVerifyRequestToJSON(json: any): MfaVerifyRequest {
    return MfaVerifyRequestToJSONTyped(json, false);
}

export function MfaVerifyRequestToJSONTyped(value?: MfaVerifyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'challengeId': value['challengeId'],
        'code': value['code'],
        'deviceId': value['deviceId'],
        'rememberMe': value['rememberMe'],
    };
}

