/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OAuthLoginRequest
 */
export interface OAuthLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof OAuthLoginRequest
     */
    provider: OAuthLoginRequestProviderEnum;
    /**
     * 
     * @type {string}
     * @memberof OAuthLoginRequest
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof OAuthLoginRequest
     */
    deviceId: string;
    /**
     * 
     * @type {boolean}
     * @memberof OAuthLoginRequest
     */
    rememberMe?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OAuthLoginRequest
     */
    deviceName?: string;
}


/**
 * @export
 */
export const OAuthLoginRequestProviderEnum = {
    Google: 'GOOGLE',
    Facebook: 'FACEBOOK',
    Github: 'GITHUB'
} as const;
export type OAuthLoginRequestProviderEnum = typeof OAuthLoginRequestProviderEnum[keyof typeof OAuthLoginRequestProviderEnum];


/**
 * Check if a given object implements the OAuthLoginRequest interface.
 */
export function instanceOfOAuthLoginRequest(value: object): value is OAuthLoginRequest {
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('deviceId' in value) || value['deviceId'] === undefined) return false;
    return true;
}

export function OAuthLoginRequestFromJSON(json: any): OAuthLoginRequest {
    return OAuthLoginRequestFromJSONTyped(json, false);
}

export function OAuthLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthLoginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': json['provider'],
        'accessToken': json['accessToken'],
        'deviceId': json['deviceId'],
        'rememberMe': json['rememberMe'] == null ? undefined : json['rememberMe'],
        'deviceName': json['deviceName'] == null ? undefined : json['deviceName'],
    };
}

export function OAuthLoginRequestToJSON(json: any): OAuthLoginRequest {
    return OAuthLoginRequestToJSONTyped(json, false);
}

export function OAuthLoginRequestToJSONTyped(value?: OAuthLoginRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': value['provider'],
        'accessToken': value['accessToken'],
        'deviceId': value['deviceId'],
        'rememberMe': value['rememberMe'],
        'deviceName': value['deviceName'],
    };
}

