/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageableObject } from './PageableObject';
import {
    PageableObjectFromJSON,
    PageableObjectFromJSONTyped,
    PageableObjectToJSON,
    PageableObjectToJSONTyped,
} from './PageableObject';
import type { EmergencyContactResponse } from './EmergencyContactResponse';
import {
    EmergencyContactResponseFromJSON,
    EmergencyContactResponseFromJSONTyped,
    EmergencyContactResponseToJSON,
    EmergencyContactResponseToJSONTyped,
} from './EmergencyContactResponse';
import type { SortObject } from './SortObject';
import {
    SortObjectFromJSON,
    SortObjectFromJSONTyped,
    SortObjectToJSON,
    SortObjectToJSONTyped,
} from './SortObject';

/**
 * 
 * @export
 * @interface PageObject
 */
export interface PageObject {
    /**
     * 
     * @type {number}
     * @memberof PageObject
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageObject
     */
    totalElements?: number;
    /**
     * 
     * @type {PageableObject}
     * @memberof PageObject
     */
    pageable?: PageableObject;
    /**
     * 
     * @type {number}
     * @memberof PageObject
     */
    size?: number;
    /**
     * 
     * @type {Array<EmergencyContactResponse>}
     * @memberof PageObject
     */
    content?: Array<EmergencyContactResponse>;
    /**
     * 
     * @type {number}
     * @memberof PageObject
     */
    number?: number;
    /**
     * 
     * @type {SortObject}
     * @memberof PageObject
     */
    sort?: SortObject;
    /**
     * 
     * @type {boolean}
     * @memberof PageObject
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageObject
     */
    last?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PageObject
     */
    numberOfElements?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PageObject
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageObject interface.
 */
export function instanceOfPageObject(value: object): value is PageObject {
    return true;
}

export function PageObjectFromJSON(json: any): PageObject {
    return PageObjectFromJSONTyped(json, false);
}

export function PageObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageObject {
    if (json == null) {
        return json;
    }
    return {
        
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'pageable': json['pageable'] == null ? undefined : PageableObjectFromJSON(json['pageable']),
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(EmergencyContactResponseFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': json['sort'] == null ? undefined : SortObjectFromJSON(json['sort']),
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageObjectToJSON(json: any): PageObject {
    return PageObjectToJSONTyped(json, false);
}

export function PageObjectToJSONTyped(value?: PageObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalPages': value['totalPages'],
        'totalElements': value['totalElements'],
        'pageable': PageableObjectToJSON(value['pageable']),
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(EmergencyContactResponseToJSON)),
        'number': value['number'],
        'sort': SortObjectToJSON(value['sort']),
        'first': value['first'],
        'last': value['last'],
        'numberOfElements': value['numberOfElements'],
        'empty': value['empty'],
    };
}

