/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatientByDayResponse
 */
export interface PatientByDayResponse {
    /**
     * 
     * @type {number}
     * @memberof PatientByDayResponse
     */
    year?: number;
    /**
     * 
     * @type {number}
     * @memberof PatientByDayResponse
     */
    month?: number;
    /**
     * 
     * @type {number}
     * @memberof PatientByDayResponse
     */
    day?: number;
    /**
     * 
     * @type {number}
     * @memberof PatientByDayResponse
     */
    count?: number;
}

/**
 * Check if a given object implements the PatientByDayResponse interface.
 */
export function instanceOfPatientByDayResponse(value: object): value is PatientByDayResponse {
    return true;
}

export function PatientByDayResponseFromJSON(json: any): PatientByDayResponse {
    return PatientByDayResponseFromJSONTyped(json, false);
}

export function PatientByDayResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatientByDayResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'year': json['year'] == null ? undefined : json['year'],
        'month': json['month'] == null ? undefined : json['month'],
        'day': json['day'] == null ? undefined : json['day'],
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function PatientByDayResponseToJSON(json: any): PatientByDayResponse {
    return PatientByDayResponseToJSONTyped(json, false);
}

export function PatientByDayResponseToJSONTyped(value?: PatientByDayResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'year': value['year'],
        'month': value['month'],
        'day': value['day'],
        'count': value['count'],
    };
}

