/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrescriptionItemRequest
 */
export interface PrescriptionItemRequest {
    /**
     * 
     * @type {string}
     * @memberof PrescriptionItemRequest
     */
    prescriptionId?: string;
    /**
     * 
     * @type {string}
     * @memberof PrescriptionItemRequest
     */
    medicineId?: string;
    /**
     * 
     * @type {string}
     * @memberof PrescriptionItemRequest
     */
    dosage?: string;
    /**
     * 
     * @type {string}
     * @memberof PrescriptionItemRequest
     */
    frequency?: string;
    /**
     * 
     * @type {string}
     * @memberof PrescriptionItemRequest
     */
    duration?: string;
    /**
     * 
     * @type {string}
     * @memberof PrescriptionItemRequest
     */
    instruction?: string;
    /**
     * 
     * @type {number}
     * @memberof PrescriptionItemRequest
     */
    quantity?: number;
}

/**
 * Check if a given object implements the PrescriptionItemRequest interface.
 */
export function instanceOfPrescriptionItemRequest(value: object): value is PrescriptionItemRequest {
    return true;
}

export function PrescriptionItemRequestFromJSON(json: any): PrescriptionItemRequest {
    return PrescriptionItemRequestFromJSONTyped(json, false);
}

export function PrescriptionItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrescriptionItemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'prescriptionId': json['prescriptionId'] == null ? undefined : json['prescriptionId'],
        'medicineId': json['medicineId'] == null ? undefined : json['medicineId'],
        'dosage': json['dosage'] == null ? undefined : json['dosage'],
        'frequency': json['frequency'] == null ? undefined : json['frequency'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'instruction': json['instruction'] == null ? undefined : json['instruction'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function PrescriptionItemRequestToJSON(json: any): PrescriptionItemRequest {
    return PrescriptionItemRequestToJSONTyped(json, false);
}

export function PrescriptionItemRequestToJSONTyped(value?: PrescriptionItemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prescriptionId': value['prescriptionId'],
        'medicineId': value['medicineId'],
        'dosage': value['dosage'],
        'frequency': value['frequency'],
        'duration': value['duration'],
        'instruction': value['instruction'],
        'quantity': value['quantity'],
    };
}

