/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicKeyCredentialParameters
 */
export interface PublicKeyCredentialParameters {
    /**
     * 
     * @type {string}
     * @memberof PublicKeyCredentialParameters
     */
    alg?: PublicKeyCredentialParametersAlgEnum;
    /**
     * 
     * @type {string}
     * @memberof PublicKeyCredentialParameters
     */
    type?: PublicKeyCredentialParametersTypeEnum;
}


/**
 * @export
 */
export const PublicKeyCredentialParametersAlgEnum = {
    _8: '-8',
    _7: '-7',
    _35: '-35',
    _36: '-36',
    _257: '-257',
    _258: '-258',
    _259: '-259',
    _65535: '-65535'
} as const;
export type PublicKeyCredentialParametersAlgEnum = typeof PublicKeyCredentialParametersAlgEnum[keyof typeof PublicKeyCredentialParametersAlgEnum];

/**
 * @export
 */
export const PublicKeyCredentialParametersTypeEnum = {
    PublicKey: 'public-key'
} as const;
export type PublicKeyCredentialParametersTypeEnum = typeof PublicKeyCredentialParametersTypeEnum[keyof typeof PublicKeyCredentialParametersTypeEnum];


/**
 * Check if a given object implements the PublicKeyCredentialParameters interface.
 */
export function instanceOfPublicKeyCredentialParameters(value: object): value is PublicKeyCredentialParameters {
    return true;
}

export function PublicKeyCredentialParametersFromJSON(json: any): PublicKeyCredentialParameters {
    return PublicKeyCredentialParametersFromJSONTyped(json, false);
}

export function PublicKeyCredentialParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicKeyCredentialParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'alg': json['alg'] == null ? undefined : json['alg'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function PublicKeyCredentialParametersToJSON(json: any): PublicKeyCredentialParameters {
    return PublicKeyCredentialParametersToJSONTyped(json, false);
}

export function PublicKeyCredentialParametersToJSONTyped(value?: PublicKeyCredentialParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alg': value['alg'],
        'type': value['type'],
    };
}

