/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PrfRegistrationInput } from './PrfRegistrationInput';
import {
    PrfRegistrationInputFromJSON,
    PrfRegistrationInputFromJSONTyped,
    PrfRegistrationInputToJSON,
    PrfRegistrationInputToJSONTyped,
} from './PrfRegistrationInput';
import type { AppId } from './AppId';
import {
    AppIdFromJSON,
    AppIdFromJSONTyped,
    AppIdToJSON,
    AppIdToJSONTyped,
} from './AppId';
import type { LargeBlobRegistrationInput } from './LargeBlobRegistrationInput';
import {
    LargeBlobRegistrationInputFromJSON,
    LargeBlobRegistrationInputFromJSONTyped,
    LargeBlobRegistrationInputToJSON,
    LargeBlobRegistrationInputToJSONTyped,
} from './LargeBlobRegistrationInput';

/**
 * 
 * @export
 * @interface RegistrationExtensionInputs
 */
export interface RegistrationExtensionInputs {
    /**
     * 
     * @type {AppId}
     * @memberof RegistrationExtensionInputs
     */
    appidExclude?: AppId;
    /**
     * 
     * @type {boolean}
     * @memberof RegistrationExtensionInputs
     */
    credProps?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RegistrationExtensionInputs
     */
    credentialProtectionPolicy?: RegistrationExtensionInputsCredentialProtectionPolicyEnum;
    /**
     * 
     * @type {boolean}
     * @memberof RegistrationExtensionInputs
     */
    enforceCredentialProtectionPolicy?: boolean;
    /**
     * 
     * @type {LargeBlobRegistrationInput}
     * @memberof RegistrationExtensionInputs
     */
    largeBlob?: LargeBlobRegistrationInput;
    /**
     * 
     * @type {PrfRegistrationInput}
     * @memberof RegistrationExtensionInputs
     */
    prf?: PrfRegistrationInput;
    /**
     * 
     * @type {boolean}
     * @memberof RegistrationExtensionInputs
     */
    uvm?: boolean;
}


/**
 * @export
 */
export const RegistrationExtensionInputsCredentialProtectionPolicyEnum = {
    UserVerificationOptional: 'userVerificationOptional',
    UserVerificationOptionalWithCredentialIdList: 'userVerificationOptionalWithCredentialIDList',
    UserVerificationRequired: 'userVerificationRequired'
} as const;
export type RegistrationExtensionInputsCredentialProtectionPolicyEnum = typeof RegistrationExtensionInputsCredentialProtectionPolicyEnum[keyof typeof RegistrationExtensionInputsCredentialProtectionPolicyEnum];


/**
 * Check if a given object implements the RegistrationExtensionInputs interface.
 */
export function instanceOfRegistrationExtensionInputs(value: object): value is RegistrationExtensionInputs {
    return true;
}

export function RegistrationExtensionInputsFromJSON(json: any): RegistrationExtensionInputs {
    return RegistrationExtensionInputsFromJSONTyped(json, false);
}

export function RegistrationExtensionInputsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrationExtensionInputs {
    if (json == null) {
        return json;
    }
    return {
        
        'appidExclude': json['appidExclude'] == null ? undefined : AppIdFromJSON(json['appidExclude']),
        'credProps': json['credProps'] == null ? undefined : json['credProps'],
        'credentialProtectionPolicy': json['credentialProtectionPolicy'] == null ? undefined : json['credentialProtectionPolicy'],
        'enforceCredentialProtectionPolicy': json['enforceCredentialProtectionPolicy'] == null ? undefined : json['enforceCredentialProtectionPolicy'],
        'largeBlob': json['largeBlob'] == null ? undefined : LargeBlobRegistrationInputFromJSON(json['largeBlob']),
        'prf': json['prf'] == null ? undefined : PrfRegistrationInputFromJSON(json['prf']),
        'uvm': json['uvm'] == null ? undefined : json['uvm'],
    };
}

export function RegistrationExtensionInputsToJSON(json: any): RegistrationExtensionInputs {
    return RegistrationExtensionInputsToJSONTyped(json, false);
}

export function RegistrationExtensionInputsToJSONTyped(value?: RegistrationExtensionInputs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'appidExclude': AppIdToJSON(value['appidExclude']),
        'credProps': value['credProps'],
        'credentialProtectionPolicy': value['credentialProtectionPolicy'],
        'enforceCredentialProtectionPolicy': value['enforceCredentialProtectionPolicy'],
        'largeBlob': LargeBlobRegistrationInputToJSON(value['largeBlob']),
        'prf': PrfRegistrationInputToJSON(value['prf']),
        'uvm': value['uvm'],
    };
}

