/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressResponse } from './AddressResponse';
import {
    AddressResponseFromJSON,
    AddressResponseFromJSONTyped,
    AddressResponseToJSON,
    AddressResponseToJSONTyped,
} from './AddressResponse';

/**
 * 
 * @export
 * @interface RegisterRequest
 */
export interface RegisterRequest {
    /**
     * 
     * @type {string}
     * @memberof RegisterRequest
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequest
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequest
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequest
     */
    phone?: string;
    /**
     * 
     * @type {Date}
     * @memberof RegisterRequest
     */
    dob?: Date;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequest
     */
    gender?: RegisterRequestGenderEnum;
    /**
     * 
     * @type {AddressResponse}
     * @memberof RegisterRequest
     */
    address?: AddressResponse;
}


/**
 * @export
 */
export const RegisterRequestGenderEnum = {
    Male: 'MALE',
    Female: 'FEMALE',
    Other: 'OTHER'
} as const;
export type RegisterRequestGenderEnum = typeof RegisterRequestGenderEnum[keyof typeof RegisterRequestGenderEnum];


/**
 * Check if a given object implements the RegisterRequest interface.
 */
export function instanceOfRegisterRequest(value: object): value is RegisterRequest {
    return true;
}

export function RegisterRequestFromJSON(json: any): RegisterRequest {
    return RegisterRequestFromJSONTyped(json, false);
}

export function RegisterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'dob': json['dob'] == null ? undefined : (new Date(json['dob'])),
        'gender': json['gender'] == null ? undefined : json['gender'],
        'address': json['address'] == null ? undefined : AddressResponseFromJSON(json['address']),
    };
}

export function RegisterRequestToJSON(json: any): RegisterRequest {
    return RegisterRequestToJSONTyped(json, false);
}

export function RegisterRequestToJSONTyped(value?: RegisterRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'fullName': value['fullName'],
        'email': value['email'],
        'password': value['password'],
        'phone': value['phone'],
        'dob': value['dob'] == null ? value['dob'] : value['dob'].toISOString().substring(0,10),
        'gender': value['gender'],
        'address': AddressResponseToJSON(value['address']),
    };
}

