/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoomRequest
 */
export interface RoomRequest {
    /**
     * 
     * @type {string}
     * @memberof RoomRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RoomRequest
     */
    roomType: RoomRequestRoomTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof RoomRequest
     */
    floorNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof RoomRequest
     */
    capacity?: number;
    /**
     * 
     * @type {string}
     * @memberof RoomRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof RoomRequest
     */
    departmentId: string;
}


/**
 * @export
 */
export const RoomRequestRoomTypeEnum = {
    Consultation: 'CONSULTATION',
    Xray: 'XRAY',
    Ultrasound: 'ULTRASOUND',
    Laboratory: 'LABORATORY',
    Procedure: 'PROCEDURE',
    Pharmacy: 'PHARMACY',
    Cashier: 'CASHIER',
    Reception: 'RECEPTION',
    WaitingArea: 'WAITING_AREA',
    Endoscopy: 'ENDOSCOPY',
    Ecg: 'ECG',
    Eeg: 'EEG',
    Dexa: 'DEXA',
    CtScan: 'CT_SCAN',
    Mri: 'MRI',
    Optometry: 'OPTOMETRY',
    Vaccination: 'VACCINATION',
    Physiotherapy: 'PHYSIOTHERAPY',
    Pft: 'PFT',
    MinorSurgery: 'MINOR_SURGERY'
} as const;
export type RoomRequestRoomTypeEnum = typeof RoomRequestRoomTypeEnum[keyof typeof RoomRequestRoomTypeEnum];


/**
 * Check if a given object implements the RoomRequest interface.
 */
export function instanceOfRoomRequest(value: object): value is RoomRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('roomType' in value) || value['roomType'] === undefined) return false;
    if (!('departmentId' in value) || value['departmentId'] === undefined) return false;
    return true;
}

export function RoomRequestFromJSON(json: any): RoomRequest {
    return RoomRequestFromJSONTyped(json, false);
}

export function RoomRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoomRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'roomType': json['roomType'],
        'floorNumber': json['floorNumber'] == null ? undefined : json['floorNumber'],
        'capacity': json['capacity'] == null ? undefined : json['capacity'],
        'description': json['description'] == null ? undefined : json['description'],
        'departmentId': json['departmentId'],
    };
}

export function RoomRequestToJSON(json: any): RoomRequest {
    return RoomRequestToJSONTyped(json, false);
}

export function RoomRequestToJSONTyped(value?: RoomRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'roomType': value['roomType'],
        'floorNumber': value['floorNumber'],
        'capacity': value['capacity'],
        'description': value['description'],
        'departmentId': value['departmentId'],
    };
}

