/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceCatalogResponse
 */
export interface ServiceCatalogResponse {
    /**
     * 
     * @type {string}
     * @memberof ServiceCatalogResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceCatalogResponse
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceCatalogResponse
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceCatalogResponse
     */
    category?: string;
    /**
     * 
     * @type {number}
     * @memberof ServiceCatalogResponse
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceCatalogResponse
     */
    description?: string;
}

/**
 * Check if a given object implements the ServiceCatalogResponse interface.
 */
export function instanceOfServiceCatalogResponse(value: object): value is ServiceCatalogResponse {
    return true;
}

export function ServiceCatalogResponseFromJSON(json: any): ServiceCatalogResponse {
    return ServiceCatalogResponseFromJSONTyped(json, false);
}

export function ServiceCatalogResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceCatalogResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'code': json['code'] == null ? undefined : json['code'],
        'name': json['name'] == null ? undefined : json['name'],
        'category': json['category'] == null ? undefined : json['category'],
        'price': json['price'] == null ? undefined : json['price'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function ServiceCatalogResponseToJSON(json: any): ServiceCatalogResponse {
    return ServiceCatalogResponseToJSONTyped(json, false);
}

export function ServiceCatalogResponseToJSONTyped(value?: ServiceCatalogResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'code': value['code'],
        'name': value['name'],
        'category': value['category'],
        'price': value['price'],
        'description': value['description'],
    };
}

