/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceOrderItemRequest
 */
export interface ServiceOrderItemRequest {
    /**
     * 
     * @type {string}
     * @memberof ServiceOrderItemRequest
     */
    serviceOrderId?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceOrderItemRequest
     */
    serviceId?: string;
    /**
     * 
     * @type {number}
     * @memberof ServiceOrderItemRequest
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceOrderItemRequest
     */
    note?: string;
}

/**
 * Check if a given object implements the ServiceOrderItemRequest interface.
 */
export function instanceOfServiceOrderItemRequest(value: object): value is ServiceOrderItemRequest {
    return true;
}

export function ServiceOrderItemRequestFromJSON(json: any): ServiceOrderItemRequest {
    return ServiceOrderItemRequestFromJSONTyped(json, false);
}

export function ServiceOrderItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceOrderItemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceOrderId': json['serviceOrderId'] == null ? undefined : json['serviceOrderId'],
        'serviceId': json['serviceId'] == null ? undefined : json['serviceId'],
        'price': json['price'] == null ? undefined : json['price'],
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function ServiceOrderItemRequestToJSON(json: any): ServiceOrderItemRequest {
    return ServiceOrderItemRequestToJSONTyped(json, false);
}

export function ServiceOrderItemRequestToJSONTyped(value?: ServiceOrderItemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serviceOrderId': value['serviceOrderId'],
        'serviceId': value['serviceId'],
        'price': value['price'],
        'note': value['note'],
    };
}

