/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceUsageResponse
 */
export interface ServiceUsageResponse {
    /**
     * 
     * @type {string}
     * @memberof ServiceUsageResponse
     */
    serviceName?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceUsageResponse
     */
    category?: string;
    /**
     * 
     * @type {number}
     * @memberof ServiceUsageResponse
     */
    usedCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ServiceUsageResponse
     */
    totalPrice?: number;
}

/**
 * Check if a given object implements the ServiceUsageResponse interface.
 */
export function instanceOfServiceUsageResponse(value: object): value is ServiceUsageResponse {
    return true;
}

export function ServiceUsageResponseFromJSON(json: any): ServiceUsageResponse {
    return ServiceUsageResponseFromJSONTyped(json, false);
}

export function ServiceUsageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceUsageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'serviceName': json['serviceName'] == null ? undefined : json['serviceName'],
        'category': json['category'] == null ? undefined : json['category'],
        'usedCount': json['usedCount'] == null ? undefined : json['usedCount'],
        'totalPrice': json['totalPrice'] == null ? undefined : json['totalPrice'],
    };
}

export function ServiceUsageResponseToJSON(json: any): ServiceUsageResponse {
    return ServiceUsageResponseToJSONTyped(json, false);
}

export function ServiceUsageResponseToJSONTyped(value?: ServiceUsageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serviceName': value['serviceName'],
        'category': value['category'],
        'usedCount': value['usedCount'],
        'totalPrice': value['totalPrice'],
    };
}

