/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpecialtyDistributionResponse
 */
export interface SpecialtyDistributionResponse {
    /**
     * 
     * @type {string}
     * @memberof SpecialtyDistributionResponse
     */
    specialty?: string;
    /**
     * 
     * @type {number}
     * @memberof SpecialtyDistributionResponse
     */
    count?: number;
}

/**
 * Check if a given object implements the SpecialtyDistributionResponse interface.
 */
export function instanceOfSpecialtyDistributionResponse(value: object): value is SpecialtyDistributionResponse {
    return true;
}

export function SpecialtyDistributionResponseFromJSON(json: any): SpecialtyDistributionResponse {
    return SpecialtyDistributionResponseFromJSONTyped(json, false);
}

export function SpecialtyDistributionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpecialtyDistributionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'specialty': json['specialty'] == null ? undefined : json['specialty'],
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function SpecialtyDistributionResponseToJSON(json: any): SpecialtyDistributionResponse {
    return SpecialtyDistributionResponseToJSONTyped(json, false);
}

export function SpecialtyDistributionResponseToJSONTyped(value?: SpecialtyDistributionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'specialty': value['specialty'],
        'count': value['count'],
    };
}

