/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LocalTime } from './LocalTime';
import {
    LocalTimeFromJSON,
    LocalTimeFromJSONTyped,
    LocalTimeToJSON,
    LocalTimeToJSONTyped,
} from './LocalTime';

/**
 * 
 * @export
 * @interface StaffScheduleDayOffRequest
 */
export interface StaffScheduleDayOffRequest {
    /**
     * 
     * @type {string}
     * @memberof StaffScheduleDayOffRequest
     */
    staffId?: string;
    /**
     * 
     * @type {Date}
     * @memberof StaffScheduleDayOffRequest
     */
    date?: Date;
    /**
     * 
     * @type {LocalTime}
     * @memberof StaffScheduleDayOffRequest
     */
    startTime?: LocalTime;
    /**
     * 
     * @type {LocalTime}
     * @memberof StaffScheduleDayOffRequest
     */
    endTime?: LocalTime;
    /**
     * 
     * @type {string}
     * @memberof StaffScheduleDayOffRequest
     */
    roomId?: string;
    /**
     * 
     * @type {string}
     * @memberof StaffScheduleDayOffRequest
     */
    reason?: string;
}

/**
 * Check if a given object implements the StaffScheduleDayOffRequest interface.
 */
export function instanceOfStaffScheduleDayOffRequest(value: object): value is StaffScheduleDayOffRequest {
    return true;
}

export function StaffScheduleDayOffRequestFromJSON(json: any): StaffScheduleDayOffRequest {
    return StaffScheduleDayOffRequestFromJSONTyped(json, false);
}

export function StaffScheduleDayOffRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StaffScheduleDayOffRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'staffId': json['staffId'] == null ? undefined : json['staffId'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'startTime': json['startTime'] == null ? undefined : LocalTimeFromJSON(json['startTime']),
        'endTime': json['endTime'] == null ? undefined : LocalTimeFromJSON(json['endTime']),
        'roomId': json['roomId'] == null ? undefined : json['roomId'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function StaffScheduleDayOffRequestToJSON(json: any): StaffScheduleDayOffRequest {
    return StaffScheduleDayOffRequestToJSONTyped(json, false);
}

export function StaffScheduleDayOffRequestToJSONTyped(value?: StaffScheduleDayOffRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'staffId': value['staffId'],
        'date': value['date'] == null ? value['date'] : value['date'].toISOString().substring(0,10),
        'startTime': LocalTimeToJSON(value['startTime']),
        'endTime': LocalTimeToJSON(value['endTime']),
        'roomId': value['roomId'],
        'reason': value['reason'],
    };
}

