/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LocalTime } from './LocalTime';
import {
    LocalTimeFromJSON,
    LocalTimeFromJSONTyped,
    LocalTimeToJSON,
    LocalTimeToJSONTyped,
} from './LocalTime';

/**
 * 
 * @export
 * @interface StaffScheduleRequest
 */
export interface StaffScheduleRequest {
    /**
     * 
     * @type {string}
     * @memberof StaffScheduleRequest
     */
    staffId?: string;
    /**
     * 
     * @type {string}
     * @memberof StaffScheduleRequest
     */
    dayOfWeek?: StaffScheduleRequestDayOfWeekEnum;
    /**
     * 
     * @type {LocalTime}
     * @memberof StaffScheduleRequest
     */
    startTime?: LocalTime;
    /**
     * 
     * @type {LocalTime}
     * @memberof StaffScheduleRequest
     */
    endTime?: LocalTime;
    /**
     * 
     * @type {boolean}
     * @memberof StaffScheduleRequest
     */
    available?: boolean;
    /**
     * 
     * @type {string}
     * @memberof StaffScheduleRequest
     */
    roomId?: string;
}


/**
 * @export
 */
export const StaffScheduleRequestDayOfWeekEnum = {
    Monday: 'MONDAY',
    Tuesday: 'TUESDAY',
    Wednesday: 'WEDNESDAY',
    Thursday: 'THURSDAY',
    Friday: 'FRIDAY',
    Saturday: 'SATURDAY',
    Sunday: 'SUNDAY'
} as const;
export type StaffScheduleRequestDayOfWeekEnum = typeof StaffScheduleRequestDayOfWeekEnum[keyof typeof StaffScheduleRequestDayOfWeekEnum];


/**
 * Check if a given object implements the StaffScheduleRequest interface.
 */
export function instanceOfStaffScheduleRequest(value: object): value is StaffScheduleRequest {
    return true;
}

export function StaffScheduleRequestFromJSON(json: any): StaffScheduleRequest {
    return StaffScheduleRequestFromJSONTyped(json, false);
}

export function StaffScheduleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StaffScheduleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'staffId': json['staffId'] == null ? undefined : json['staffId'],
        'dayOfWeek': json['dayOfWeek'] == null ? undefined : json['dayOfWeek'],
        'startTime': json['startTime'] == null ? undefined : LocalTimeFromJSON(json['startTime']),
        'endTime': json['endTime'] == null ? undefined : LocalTimeFromJSON(json['endTime']),
        'available': json['available'] == null ? undefined : json['available'],
        'roomId': json['roomId'] == null ? undefined : json['roomId'],
    };
}

export function StaffScheduleRequestToJSON(json: any): StaffScheduleRequest {
    return StaffScheduleRequestToJSONTyped(json, false);
}

export function StaffScheduleRequestToJSONTyped(value?: StaffScheduleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'staffId': value['staffId'],
        'dayOfWeek': value['dayOfWeek'],
        'startTime': LocalTimeToJSON(value['startTime']),
        'endTime': LocalTimeToJSON(value['endTime']),
        'available': value['available'],
        'roomId': value['roomId'],
    };
}

