/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RoomResponse } from './RoomResponse';
import {
    RoomResponseFromJSON,
    RoomResponseFromJSONTyped,
    RoomResponseToJSON,
    RoomResponseToJSONTyped,
} from './RoomResponse';
import type { LocalTime } from './LocalTime';
import {
    LocalTimeFromJSON,
    LocalTimeFromJSONTyped,
    LocalTimeToJSON,
    LocalTimeToJSONTyped,
} from './LocalTime';
import type { StaffResponse } from './StaffResponse';
import {
    StaffResponseFromJSON,
    StaffResponseFromJSONTyped,
    StaffResponseToJSON,
    StaffResponseToJSONTyped,
} from './StaffResponse';

/**
 * 
 * @export
 * @interface StaffScheduleTemplateResponse
 */
export interface StaffScheduleTemplateResponse {
    /**
     * 
     * @type {string}
     * @memberof StaffScheduleTemplateResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof StaffScheduleTemplateResponse
     */
    dayOfWeek?: StaffScheduleTemplateResponseDayOfWeekEnum;
    /**
     * 
     * @type {LocalTime}
     * @memberof StaffScheduleTemplateResponse
     */
    startTime?: LocalTime;
    /**
     * 
     * @type {LocalTime}
     * @memberof StaffScheduleTemplateResponse
     */
    endTime?: LocalTime;
    /**
     * 
     * @type {boolean}
     * @memberof StaffScheduleTemplateResponse
     */
    active?: boolean;
    /**
     * 
     * @type {StaffResponse}
     * @memberof StaffScheduleTemplateResponse
     */
    staff?: StaffResponse;
    /**
     * 
     * @type {RoomResponse}
     * @memberof StaffScheduleTemplateResponse
     */
    room?: RoomResponse;
}


/**
 * @export
 */
export const StaffScheduleTemplateResponseDayOfWeekEnum = {
    Monday: 'MONDAY',
    Tuesday: 'TUESDAY',
    Wednesday: 'WEDNESDAY',
    Thursday: 'THURSDAY',
    Friday: 'FRIDAY',
    Saturday: 'SATURDAY',
    Sunday: 'SUNDAY'
} as const;
export type StaffScheduleTemplateResponseDayOfWeekEnum = typeof StaffScheduleTemplateResponseDayOfWeekEnum[keyof typeof StaffScheduleTemplateResponseDayOfWeekEnum];


/**
 * Check if a given object implements the StaffScheduleTemplateResponse interface.
 */
export function instanceOfStaffScheduleTemplateResponse(value: object): value is StaffScheduleTemplateResponse {
    return true;
}

export function StaffScheduleTemplateResponseFromJSON(json: any): StaffScheduleTemplateResponse {
    return StaffScheduleTemplateResponseFromJSONTyped(json, false);
}

export function StaffScheduleTemplateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StaffScheduleTemplateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'dayOfWeek': json['dayOfWeek'] == null ? undefined : json['dayOfWeek'],
        'startTime': json['startTime'] == null ? undefined : LocalTimeFromJSON(json['startTime']),
        'endTime': json['endTime'] == null ? undefined : LocalTimeFromJSON(json['endTime']),
        'active': json['active'] == null ? undefined : json['active'],
        'staff': json['staff'] == null ? undefined : StaffResponseFromJSON(json['staff']),
        'room': json['room'] == null ? undefined : RoomResponseFromJSON(json['room']),
    };
}

export function StaffScheduleTemplateResponseToJSON(json: any): StaffScheduleTemplateResponse {
    return StaffScheduleTemplateResponseToJSONTyped(json, false);
}

export function StaffScheduleTemplateResponseToJSONTyped(value?: StaffScheduleTemplateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'dayOfWeek': value['dayOfWeek'],
        'startTime': LocalTimeToJSON(value['startTime']),
        'endTime': LocalTimeToJSON(value['endTime']),
        'active': value['active'],
        'staff': StaffResponseToJSON(value['staff']),
        'room': RoomResponseToJSON(value['room']),
    };
}

