/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SwitchMfaRequest
 */
export interface SwitchMfaRequest {
    /**
     * 
     * @type {string}
     * @memberof SwitchMfaRequest
     */
    mfaType?: SwitchMfaRequestMfaTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SwitchMfaRequest
     */
    challengeId?: string;
}


/**
 * @export
 */
export const SwitchMfaRequestMfaTypeEnum = {
    Totp: 'TOTP',
    Sms: 'SMS',
    Email: 'EMAIL',
    PushNotification: 'PUSH_NOTIFICATION',
    Passkey: 'PASSKEY',
    EmailVerification: 'EMAIL_VERIFICATION'
} as const;
export type SwitchMfaRequestMfaTypeEnum = typeof SwitchMfaRequestMfaTypeEnum[keyof typeof SwitchMfaRequestMfaTypeEnum];


/**
 * Check if a given object implements the SwitchMfaRequest interface.
 */
export function instanceOfSwitchMfaRequest(value: object): value is SwitchMfaRequest {
    return true;
}

export function SwitchMfaRequestFromJSON(json: any): SwitchMfaRequest {
    return SwitchMfaRequestFromJSONTyped(json, false);
}

export function SwitchMfaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwitchMfaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mfaType': json['mfaType'] == null ? undefined : json['mfaType'],
        'challengeId': json['challengeId'] == null ? undefined : json['challengeId'],
    };
}

export function SwitchMfaRequestToJSON(json: any): SwitchMfaRequest {
    return SwitchMfaRequestToJSONTyped(json, false);
}

export function SwitchMfaRequestToJSONTyped(value?: SwitchMfaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mfaType': value['mfaType'],
        'challengeId': value['challengeId'],
    };
}

