/* tslint:disable */
/* eslint-disable */
/**
 * Clinic Management API
 * API documentation for the Clinic Management system
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressResponse } from './AddressResponse';
import {
    AddressResponseFromJSON,
    AddressResponseFromJSONTyped,
    AddressResponseToJSON,
    AddressResponseToJSONTyped,
} from './AddressResponse';

/**
 * 
 * @export
 * @interface UserProfileRequest
 */
export interface UserProfileRequest {
    /**
     * 
     * @type {string}
     * @memberof UserProfileRequest
     */
    fullName?: string;
    /**
     * 
     * @type {Date}
     * @memberof UserProfileRequest
     */
    dateOfBirth?: Date;
    /**
     * 
     * @type {AddressResponse}
     * @memberof UserProfileRequest
     */
    address?: AddressResponse;
    /**
     * 
     * @type {string}
     * @memberof UserProfileRequest
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileRequest
     */
    avatarUrl?: string;
}

/**
 * Check if a given object implements the UserProfileRequest interface.
 */
export function instanceOfUserProfileRequest(value: object): value is UserProfileRequest {
    return true;
}

export function UserProfileRequestFromJSON(json: any): UserProfileRequest {
    return UserProfileRequestFromJSONTyped(json, false);
}

export function UserProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'dateOfBirth': json['dateOfBirth'] == null ? undefined : (new Date(json['dateOfBirth'])),
        'address': json['address'] == null ? undefined : AddressResponseFromJSON(json['address']),
        'phone': json['phone'] == null ? undefined : json['phone'],
        'avatarUrl': json['avatarUrl'] == null ? undefined : json['avatarUrl'],
    };
}

export function UserProfileRequestToJSON(json: any): UserProfileRequest {
    return UserProfileRequestToJSONTyped(json, false);
}

export function UserProfileRequestToJSONTyped(value?: UserProfileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fullName': value['fullName'],
        'dateOfBirth': value['dateOfBirth'] == null ? value['dateOfBirth'] : value['dateOfBirth'].toISOString().substring(0,10),
        'address': AddressResponseToJSON(value['address']),
        'phone': value['phone'],
        'avatarUrl': value['avatarUrl'],
    };
}

